### ISSUE TITLE
Discovery: choose a simple django CMS

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#10]
django-cms? wagtail?

**Comment by justinabrahms** [comment]
http://www.revsys.com/blog/2015/apr/29/wagtail-best-django-cms/ -- This is a pretty strong recommendation for wagtail.

Beyond that, from what I see, they have a pretty slick backend, which might hit @Ferdi's desire to have something markedly better than Drupal (from a user's perspective). https://wagtail.io/

**Comment by Ferdi** [comment]
I wonder how difficult is to make it so that each course team / department author only the pages relevant to their program.

**Comment by justinabrahms** [comment]
It looks like they have some amount of support for permissioning. I would like to push that requirement out for consideration later.

**Comment by Ferdi** [comment]
That's currently a static one-page website. For this version, can we move that exact page to micromasters.mit.edu/scm ?

**Comment by justinabrahms** [comment]
We should try to incorporate SCM into the CMS as it's written, rather than special casing it. Making it a special case b/c they have a website already effectively means doing double work. Once for the CMS case, once for a static-website-serving case.

So to answer your question, yes we could put a static website on that url, but it's going to be more work and will not benefit the product directly in the longer term. The longer term goal would be to have everyone on the CMS.

**Comment by justinabrahms** [comment]
w/r/t the CMS.. What should the pages be like? One single free-form text field that they can enter? Big header images? Something different?

The way wagtail works, you define a class for each page type, then users can pick which page type they want to add to the cms. Getting a sense of what the page types are and what they look like is going to be necessary to proceed with this task.

**Comment by justinabrahms** [comment]
I did a spike of work on wagtail: https://github.com/mitodl/micromasters/compare/cms

It's a pretty simple start, but is enough to show a course listing in bare html of a homepage and a program page which allows a user to enter free-form text. We'd likely want sub-pages from these program pages, but we need to define what those look like and what fields they'd need to have before progressing much futher.

cc @annagav because that spike has a start to a very bare-bones (in so much as we're rendering some courses) homepage. It gives a sense of what it takes to do that in wagtail.

![terrible-homepage](https://cloud.githubusercontent.com/assets/3853/13509031/87abaeee-e157-11e5-97d3-ecdc73eaa937.png)

**Comment by pdpinch** [comment]
Closing this. If we do go with a django CMS, it will be wagtail.
