### ISSUE TITLE
Financial Aid: Review Actions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1049]
# Acceptance Criteria

- [ ] API endpoint to mark documents received
  - [ ] when documents are received, an e-mail is sent to the learner
- [ ] API endpoint to approve a request (at a particular tier)
  - [ ] when a request is approved, an e-mail is sent to the learner
- [ ] API endpoint to reject a request
  - [ ] when a request is rejected, an e-mail is sent to the learner
  - [ ] On rejection, change tier to full price
- [ ] API endpoint to email an applicant
- [ ] Limit API endpoints to staff in the appropriate program

**Comment by alvinsiu** [comment]
Removed - [ ] API endpoint to download a document (via one-time link)

**Comment by pdpinch** [comment]
cleaned up the description, including adding:

- [ ] API endpoint to mark documents received

**Comment by alvinsiu** [comment]
@pdpinch Just wanted to ask a clarification question about the financial aid workflow.  We're making the assumption that in order to mark documents as received (and send the email), the current status of their financial aid request MUST be "pending-docs".  Similarly, in order to mark a request as "approved" or "rejected", the current status of the financial aid request MUST be "pending-manual-approval".  This way, if anyone attempts to mark documents received after they've been received will not cause an email to be sent, and if anyone attempts to accept or reject an application that hasn't had docs received will not approve/reject when waiting for documents.

Is this the correct story/workflow?  Thanks!

**Comment by Ferdi** [comment]
@alvinsiu 

> if anyone attempts to mark documents received *after* they've been received will not cause an email 
> to be sent

you mean *before* right ?

**Comment by Ferdi** [comment]
@pdpinch does it make sense to link to the e-mail templates here ?

**Comment by alvinsiu** [comment]
@Ferdi Marking a financial aid request's status as documents received is coupled with sending the email.  What I mean is that if the financial aid request is not currently pending documents, that is its status is anything but "pending-documents", trying to set it as documents received will fail, consequently no email will be sent to the learner. So yes, no email will be sent before, and also no email will be sent after either.

Let me know if that's still unclear, and I'm happy to further clarify!

**Comment by Ferdi** [comment]
@alvinsiu Sorry, not particularly familiar with statuses. 

Here is the use case I have in mind where I am the learner and you are the reviewer:
  
- I as a learner, mail my documents.  
- 2 weeks have past , and I'm not sure if you received the docs. So I start sending you e-mails (thing that we want to avoid)
- You as a reviewer receive the docs but did not have time to review.  You would like to send an appropriate e-mail to the learner -- That you have received the docs and will review them soon

Make sense ?

**Comment by alvinsiu** [comment]
Yup, that makes sense and is exactly how it works!  The clarification I asked was just make sure we have the right validation to ensure learners only receive that email once.
