### ISSUE TITLE
Financial Aid: Coupon inventory alerts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1051]
Since creating more coupons is a manual process, MicroMasters admins need to be notified when the inventory of coupons is low or insufficient to meet all learner requests. 

# Acceptance Criteria

- [x] Coupon expiration alert
- [ ] Insufficient unallocated coupons alert (take into account approved users who don't yet have a coupon)

**Comment by zags** [comment]
@giocalitri suggested always issuing coupons that expire after the course run is complete.  Assuming we can always do this, it eliminates the need for the coupon expiration alert and solves some other corner cases surrounding coupon expiration as well.  We do still need the insufficient unallocated coupons alert

**Comment by zags** [comment]
Just a note on how we determine when we are out of coupons for a tier.  Obviously coupons that have been associated with a user are not available.  We also want to take into account users who have been approved for financial aid but not allocated a coupon for that course yet.  However, because courses are offered multiple times (through course runs), the important thing to check for is that a user has not been allocated a coupon yet for that *course*, not that *course run*.

For example, we have 20 coupons.  There are 15 users who have been approved for financial aid.  6 of them have been allocated a coupon for the current run of a given course.  5 of them have been been allocated a coupon for a previous run of that course.  4 of them have never been allocated a coupon for any run of that course.  We should estimate that we have 10 coupons remaining.

**Comment by giocalitri** [comment]
Coupons will be tied to a specific course_run, not a course. the concept of course does not exist in edX.
That means that each run will have its own coupons.

**Comment by pdpinch** [comment]
We have some options for how edX associates coupons with course_runs. For simplicity's sake, Giovanni and I were thinking that a strict relationship was best: a coupon can only work with a specific course run. 

Alternately, edX allows for a query to match a coupon with multiple course_runs, or multiple courses. However, given the vagaries of course numbering, it seems best to avoid that route. 

Let me know if you disagree and I'll dig up the documentation or, if there is none, some code pointers.

**Comment by zags** [comment]
I know coupons are attached to a specific course run.  I'm assuming that here.  I'm talking about estimating the number of people who are going to need coupons but do not yet have them allocated.

People are approved for financial aid on the program level.  Then, people enroll in course runs.  We need to have enough coupons in reserve for the people who have been approved for financial aid but not yet enrolled in a run of that course.  Let me clarify the example.

For example, we have 20 coupons for Econ 101, fall 2017. There are 15 users who have been approved for financial aid for the Econ program. 6 of them have been allocated a coupon for Econ 101 fall 2017. 5 of them were allocated a coupons for Econ 101, fall 2016. 4 of them have never been allocated a coupon for any run of Econ 101.  It is obvious from this that we have 14 unallocated coupons for Econ 101, fall 2017.  But at least some of these 14 will be needed by users who have been approved for financial aid but not yet assigned a coupon.  How many of these 14 coupons do we hold in reserve?
A) 5 coupons, for just the people who haven't ever enrolled in Econ 101
B) 9 coupons, for all the people who haven't enrolled in Econ 101, fall 2017

**Comment by pdpinch** [comment]
Executive decision from today: we won't be using coupons. 

Instead we'll handle transactions in the MM portal. Fulfillment will be an automatic enrollment into an audit track at edx.org plus a registering for a MM certificate to be granted when all courses and exams are passed.
