### ISSUE TITLE
Move course price from CoursePrice into Program

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1144]
This isn't an urgent change but at the same time I feel like we will want this soon for consistency's sake.

**Comment by gsidebo** [comment]
To clarify, I think this issue is suggesting that we move `CoursePrice` into courses/models.py.

Just an example of an unfortunate side effect of this model being defined in ecommerce instead of courses: the need to import `CoursePrice` within `courses.models.Program#get_course_price`. 

This issue will involve creating the necessary migrations that will change the name of the table associated with the model (and, if necessary, migrate existing data from one table to the other).

**Comment by noisecapella** [comment]
@gsidebo This is suggesting removing the `CoursePrice` model entirely and storing only a `price` field on `Program`
