### ISSUE TITLE
Program pages: Unique url for each tab

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1191]
Navigation menu items currently don't get a unique url. This create a problem when someone wants to e-mail/share a particular page (e.g. FAQ page)

**Comment by pdpinch** [comment]
@Ferdi are hashes OK for this, or do we need more?

I'm wondering in particular, once we add categories to the FAQ (#1190) if we might need to target particular parts of the FAQ page.

**Comment by Ferdi** [comment]
I'm not really sure why we are implementing these tabs in JS.   For example, in terms of SEO, are metatags going to change based on where you are homepage or FAQ?

**Comment by pdpinch** [comment]
I don't think there was a particularly strong reason for implementing this in JavaScript. It does make the UI more responsive, but other than that we move to one page per tab. 

How would the metatags be different for a program page and a program FAQ? We can give them different title, keyword and description, but I don't think that would have much of an effect on SEO (other than potentially getting a hit for each page, instead of just one).

**Comment by roberthouse54** [comment]
I suggest that we hold off on any further changes to this page. The SEO is not a huge issue in my opinion, and we can revisit after the MVP launch if needed.

**Comment by pdpinch** [comment]
@Ferdi and I spoke this morning and came to the same conclusion. We'll probably revisit when we get to work on #597

**Comment by pdpinch** [comment]
Since we've discovered a bug in the JavaScript implementation, it seems wisest to change direction and go with a full URL for each tab.
