### ISSUE TITLE
Capacity testing for production app

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1218]
Do some simple load testing so we have an idea how many clients we can server with a basic production set up on Heroku.

**Comment by blarghmatey** [comment]
In order to simulate the upper bound of the estimated number of concurrent users we are planning to use the [Locust](https://locust.io) project to script a typical set of HTTP requests to the Micromasters API. Once we have that set of interactions defined we will deploy to a set of servers with enough capacity to simulate ~10,000 concurrent users and monitor the output of Heroku metrics, NewRelic, and process logs. Those findings will then be used to appropriately tune our capacity in Heroku along with any necessary bug fixes.

**Comment by blarghmatey** [comment]
Running the load test resulted in a few findings and led to some follow-up tasks:
- The per-dyno capacity at the time that the test was run was between 50-100 concurrent users, with significant lag at the upper end of that range.
- Scaling horizontally by adding more dynos alleviated performance issues
- There are a number of queries, particularly in the dashboard, that are in need of optimization for N+1 issues
- The app was making a new DB connection for every transaction, resulting in excess latency and I/O overhead

The first action taken after the load testing was to configure Django to use persistent connections which resulted in an immediate performance gain and rose our per-dyno capacity to the 150-200 concurrent user range.
