### ISSUE TITLE
Truncate the Course Descriptions on the Program page, with a link to Read More on Edx

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1237]
The course descriptions are a bit too long on the Program Page, and we also want to let users know that the link will go to edX. 

The solution is to show the description in a popup when the user clicks the description link. This popup will include the course name, the description and a link to "View on edX". Clicking outside of the popup should make it close. For mobile, the popup should take up the full width and height of the screen (minus a margin all around), and be scrollable, with an "X" to close the popup for mobile view.

**Comment by annagav** [comment]
What is the limit on the length of the paragraph?

**Comment by pdpinch** [comment]
Looks like 150 characters to me.

**Comment by roberthouse54** [comment]
Let's test it and see which character length works best.

**Comment by roberthouse54** [comment]
@ferdi Do we want to switch to a popup for this instead? Like this:

![course_desc_popup](https://cloud.githubusercontent.com/assets/20047260/19278030/d902b912-8fa9-11e6-9bbc-5bec10c7cad7.jpg)

**Comment by Ferdi** [comment]
Considering the current overall design and everything, I personally think this is a better option.

**Comment by pdpinch** [comment]
@roberthouse54 can you update the description to match your new image?

@annagav make sure you're using the latest designs when you work on this

**Comment by roberthouse54** [comment]
See updated description above.

**Comment by singingwolfboy** [comment]
@roberthouse54: the UI element that you're using in the mockup above resembles a tooltip, rather than a popup. [Material Design Lite has a tooltip component](https://material.google.com/components/tooltips.html), but the official usage recommendations don't match with how you've mocked this up. In particular, MDL recommends _not_ using a directional arrow, and not filling tooltips with rich text and a lot of information. They seem to be designed as short labels, rather than as fully-featured components of a UI. [Bootstrap also has a tooltip component](http://getbootstrap.com/javascript/#tooltips), but it also recommends using them for short labels.

I believe that the standard UI element for displaying rich content like this is a modal window. [MDL has a "dialog" component that does this](https://material.google.com/components/dialogs.html), [and Bootstrap calls it a "modal"](http://getbootstrap.com/javascript/#modals). Modals are more conducive to rich content, and it's easier to read this content long-form, since there's an explicit "dismiss" action to close the modal. (Tooltips usually disappear when the mouse moves away from the element that is being described, so it's easy to close them by accident.)

Would you like me to implement this as a tooltip, the way you have in the mockup above? Or should I use a modal instead?

**Comment by Ferdi** [comment]
@singingwolfboy I think Rob had in mind something like [popover](http://getbootstrap.com/javascript/#popovers) .   This looks like an implementation  https://clever.com/schools/partners

Does material design has anything like that ?   All I could find was [this thread ](http://ux.stackexchange.com/questions/76332/material-design-solution-for-popovers)

**Comment by roberthouse54** [comment]
I don't really think a dialog is correct for this. Ferdi is right... I was thinking more about this popup bootstrap component. This component is really just to display more content.
