### ISSUE TITLE
Move Postgres to RDS

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1677]
Move the production database to AWS RDS

**Comment by pdpinch** [comment]
Can you add something to the description to explain why?

**Comment by blarghmatey** [comment]
The current database configured for use with Micromasters has fairly limited resources (1 GB ram, 120 connections, no HA) and the price for Heroku databases increases drastically for any corresponding increase in sizing. The price for RDS is more reasonable for a larger DB instance with HA enabled as well as exposing far more configuration parameters for performance tuning and access management. The current database instance being used for the production Micromasters instance has insufficient performance capabilities for the current state of the application and the intended scale.

**Comment by pdpinch** [comment]
We'll need to update Ike on this change.

**Comment by pdpinch** [comment]
This is done now, right? 

We still need to update Ike.

**Comment by blarghmatey** [comment]
Not officially. I haven't updated the production app to use it yet because I was doing load testing. I'm going to do one more round of that today and then get it updated on the production instance. I'll also need to touch base with Ike about how he wants to access the data. I can either set up a daily dump to S3 or just create a read-only account for him to use.

**Comment by pdpinch** [comment]
What's the status on this?

**Comment by blarghmatey** [comment]
This is now complete. The only remaining task is to set up a new export to S3 for the IR team.
