### ISSUE TITLE
performance: enable gzip compression

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1681]
not sure if the best way to do this is with django middleware, or in uwsgi, or someplace else

**Comment by pdpinch** [comment]
create gzip files as part of build pipeline & configure uswsgi to serve if present

**Comment by noisecapella** [comment]
@blarghmatey How should I go about this?

**Comment by pdpinch** [comment]
@rhysyngsun has some experience with this.

**Comment by rhysyngsun** [comment]
@noisecapella http://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html#gzip-uwsgi-1-9

**Comment by noisecapella** [comment]
I read [the WhiteNoise faq](http://whitenoise.evans.io/en/stable/#shouldn-t-i-be-pushing-my-static-files-to-s3-using-something-like-django-storages) and I'm not sure we should precompile the static assets here. Heroku has [instructions](https://devcenter.heroku.com/articles/django-assets) for integrating WhiteNoise. Any thoughts on this direction?

**Comment by rhysyngsun** [comment]
@noisecapella it depends on where we ultimately want to end up with how we handle static assets. I know we've discussed being able to set far-future cache headers on content (#1662) and that we want to possibly serve over a CDN at some point (#1661). That typically requires an asset naming/hashing technique like [described here for webpack](https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95#.i1a22rdfl). Because the filenames are uniqued off the content you can just push the hashed filenames to the CDN. Typically you'd keep older versions of assets around for at least a little bit (or indefinitely if you don't care to solve that problem) so you don't break the user experience by having a file fail to load, which I suspect isn't possible under WhiteNoise.

Also, the FAQ item is a little dated. Yes, S3 can't server gzip content correctly, but if [fronted by Cloudfront, it can](https://github.com/evansd/whitenoise/issues/59#issuecomment-182463474).

Happy to discuss / whiteboard if any of this is unclear.

**Comment by rhysyngsun** [comment]
Also, here's a link to AWS' docs on serving gzipped content: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by pdpinch** [comment]
This was closed prematurely. The code is merged but we're not yet doing it in production. 

The next step is to do some testing on micromasters-rc. Assigning to Tobias to coordinate.
