### ISSUE TITLE
Registration prerequisites 

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#174]
From my discussion with Erdin:

Currently ( I think) , anyone with an edx.org account can register in the MIT Micromasters portal.  We need to change that so only registered MM learners are allowed to create an account.  A couple of sugestions:
- Explain the eligibility somewhere in the front page 
- If the learner tries to "login with edx" anyway we verify their eligibility, we show a message that explain to the user why they are not eligible and what they need to do next to become eligible.

**Comment by giocalitri** [comment]
@Ferdi : Can you please define `registered MM learners`?

**Comment by Ferdi** [comment]
@giocalitri  I think it means "paid certificate" if I have the term right.

**Comment by giocalitri** [comment]
The problem with this is that for querying if the user has at least one paid enrollment, we need she to login because we need her edX `access_token`.

Now we can work around this and remove her user if after she login and we realize she does not have a paid course.

Anyway this sounds a bit silly to me, because I imagine it would be much better for the user to create an account but disable everything until they enroll in a program and pay.
But even this sounds weird, because it means that the user will be never able to enroll in micromasters from the micromasters website, but she need to enroll and pay on edX first.
But even if this is fine, how is the user supposed to know what is the right course to enroll if she has not access to the micromasters website?

To be fair I really would like this user flow to be explained in details to me.

**Comment by Ferdi** [comment]
Agree with you.  I think we are saying the same thing.  We can talk briefly offline and update this issue accordingly.

**Comment by pdpinch** [comment]
@Ferdi what's the status of this?

**Comment by pdpinch** [comment]
@Ferdi can we close this?

It seems like we'll need to consider this issue on a feature-by-feature basis going forward, but we don't have anything in the pipeline right now that it would affect.

**Comment by Ferdi** [comment]
For users that are not enrolled in any MM course, What happens after they fill in their profile data ?

**Comment by pdpinch** [comment]
Currently, they have access to the student dashboard, which should encourage them to enroll in a SCM course.

**Comment by Ferdi** [comment]
It's sort of OK for now.  Here is a use case that it doesn't quite work.  I register with MM but I'm not interested in SCM MM.

**Comment by pdpinch** [comment]
@ferdi we have some designs for this now, so we may be ready to start working on implementation:

Gated dashboard: https://invis.io/2C89UKP4U#/179729587_Dashboard_Gated
Access blocked: https://invis.io/2M89UKVYK#/179740120_Gated_Access_Blocked

**Comment by Ferdi** [comment]
It looks like we went in the direction of allowing anyone to register.   Closing this.
