### ISSUE TITLE
Mailgun deliveries are failing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1744]
Elastalert notified us about two Mailgun delivery failures on Thursday. I believe one was from micromasters-rc and the other was from prod.

**Comment by blarghmatey** [comment]
The failures were due to the same issue we have been having with the MIT mail gateway sending too many delay responses. Because our IP doesn't have a high enough reputation, messages from our Mailgun account are placed at the bottom of the priority rank which means that if there are other messages being handled at the time of attempted delivery then we will receive a delay response. If the level of traffic to MIT doesn't decrease enough then our messages eventually reach the retry limit and fail.

I checked our shared IP against mxtoolbox.com and verified that we are not blacklisted.
