### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2013]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/169629858/

```
RuntimeError: cannot join current thread
  File "newrelic/core/agent.py", line 232, in uwsgi_atexit_callback
    self._atexit_shutdown()
  File "newrelic/core/agent.py", line 670, in _atexit_shutdown
    self.shutdown_agent()
  File "newrelic/core/agent.py", line 682, in shutdown_agent
    self._harvest_thread.join(timeout)
  File "python3.5/threading.py", line 1051, in join
    raise RuntimeError("cannot join current thread")

RuntimeError: cannot join current thread
```

**Comment by pdpinch** [comment]
I'm not sure if this is a significant issue. It's only happened a few times in production.

**Comment by pdpinch** [comment]
The last time this happened in production was Wednesday, 12/7. See https://sentry.io/mit-office-of-digital-learning/micromasters/issues/169629858/events/4688333729/

**Comment by blarghmatey** [comment]
This happens when the uWSGI process receives the SIGTERM signal during shutdown. For example, when a new configuration value is set and the process is restarted. It does not pose any functional issues. The source of the message is that the parent process is attempting to call join on the thread which will allow it to block until the child threads have stopped but the threads that it is trying to join have likely already stopped.
