### ISSUE TITLE
Collect more GA events on signup

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2040]
We should collect more GA events to provide a more detailed funnel

**Comment by pdpinch** [comment]
We already have #132 and #1919. Do you have something different and more specific in mind?

**Comment by noisecapella** [comment]
I was actually thinking of tracking each field in the profile, both focus and visibility. Maybe it would be helpful in seeing where people stop to think or don't continue forward

**Comment by noisecapella** [comment]
Also when the photo dialog opens. If it opens and they don't click 'save' it might indicate a bug or UX issue

**Comment by roberthouse54** [comment]
Just a couple quick comments:

Our goal here should be figuring out what is happening at a high level. For example:

1. What is the funnel drop-off from page to page?
2. If users are dropping off at any point, why are they dropping off?
3. Are users deciding to not fill out the form, or are they having errors that are keeping them from proceeding from one step to another?
4. Are there other problems that are keeping people from completing the form? (language, accessibility, etc)

I think we assume that a certain percentage of users is bouncing from Step 1 just because they see a long from, and decide not to fill it out. We should be able to figure this out by looking at all the users who land on Step 1, and then never focus on any fields.

I do not know exactly how we can figure out if there are technical problems keeping people from going from one page to another. But presumably, adding an event for every field, and also tracking validation errors, is the way to go.

**Comment by pdpinch** [comment]
Proposal for actual things to track:

- [ ] URL event for each page of the form
- [ ] URL event for successful completion of the form
- [ ] events for interacting with each field
