### ISSUE TITLE
Financial Aid: Too many users need to change their income statement after submitting

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2072]
This is far and away our number one support issue. 

We need to find a way to warn users that they can't change their income statement after it's submitted. 

Some possibilities:

- stronger warning text
- "Are you sure" dialog
- confirmation dialog, e.g. "You entered an income of $xxx." and give user a chance to cancel

**Comment by roberthouse54** [comment]
When you say "after it's submitted" I assume you mean after the user has calculated their cost in the Cost Calculator? I am trying to figure out why this is such a big issue. My guess is that users low ball their income in hopes of getting a reduced price, then learn that they need to submit documents verifying their income (?) And then want to change the income they reported. Is that right?

**Comment by pdpinch** [comment]
I'm seeing two cases:

1. People who click on "Skip and pay full price" without understanding what it means:

> I made a mistake by clicking on "pay the full price" in my dashboard, could you please undo that? Many thanks in advance !

> I chose to provide income from where I live and work but accidentally clicked the option to pay full. Now I can't go back to the option to provide proof of income. How can I do it? Thanks in advance.

2. And some who enter the wrong income data. One factor hear is that I think they don't realize they may have to document it. 

> I have just created my profile on the portal and have entered. I am currently not employed and have income from other sources. However, in the later section I realised that the income refers to the household income. Kindly suggest, how do I edit the income details providing the household income to recalculate the applicable fee for the courses.

**Comment by roberthouse54** [comment]
We had some hesitation about letting people calculate their cost multiple times, because we thought they would just game it until they got the best price. I am ok with letting people recalculate their cost, but just wondering if we have concerns about this behavior. I am also curious how many of these support complaints we have received per the number of overall submissions.

**Comment by pdpinch** [comment]
We don't want to let learners recalculate their costs at this time, just make it clearer to them that they can't change their mind easily.

**Comment by pdpinch** [comment]
In terms of numbers, I've processed 62 requests so far, out of 2846 requests. That's between 2 and 3% of financial aid requests. Not huge, but it is taking up the bulk of my support time.

**Comment by roberthouse54** [comment]
How about we do this:

Cost Calculator: To clarify, add a link to “Read full instructions” and change “Income” to “Household Income”.

Pay Full Price confirmation dialog: Add a sentence in bold: “If you choose to pay full price, you will not be able to undo this, and calculate a reduced price later. ”

Confirm Income Dialog: Show this dialog when the user clicks “Calculate” from the Cost Calculator

![image](https://cloud.githubusercontent.com/assets/20047260/21618539/5fcf20c4-d1b9-11e6-8da8-be3cbf28889f.png)

**Comment by pdpinch** [comment]
Do we need another button on the 3rd dialog, labelled "Continue" or something like that?

**Comment by roberthouse54** [comment]
Yes we do... if we go this route.

**Comment by pdpinch** [comment]
Based on our discussion with Anna on 1/5, I think we should rescope this issue to just doing:

1. Change the heading of the cost calculator to replace the word "calculator" with something more permanent.
2. Change the button text from "Calculate" to "Submit" 

Depending on the response from DEDP, we may also create an anonymous calculator that would be available for users before they have registered. If we do this, I'll open a new issue for that. 

FYI @roberthouse54 @Ferdi

**Comment by pdpinch** [comment]
@roberthouse54 can you recommend a new header for the cost calculator ([#1 above](https://github.com/mitodl/micromasters/issues/2072#issuecomment-270907691))

**Comment by roberthouse54** [comment]
I think something like "Apply for Reduced Course Pricing"

**Comment by roberthouse54** [comment]
This is a simple-seeming change, but I think we will want to make several more text changes to go along with this. 

1. The feature is called "Personalized Course Pricing", so this should be the name of the card. The button in the card should be "Apply Now".
2. The modal title should be "Apply for Personalized Course Pricing".
3. The button in the modal should be "Submit Application".

Other small changes I would recommend:

1. Currently the buttons say "Calculate Cost" when the user has not yet submitted the application for Personalized Pricing. Since we are moving away from the Cost Calculator wording, we need to change this also. My suggestion is to remove this text from the buttons completely. (We have heard that users were confused by this anyway.) Instead we simply disable the buttons, and put a message at the top of the course card that says "Your need to apply for Personalized Course pricing before you can enroll. Or you can audit courses for FREE and upgrade to the MicroMasters Program later." --- the second sentence here was an change requested by marketing which we never made.
2. A minor copy change: "Pay Full Price" ---> "Skip and Pay Full Price"
3. Buttons currently say "Pay Now - $1000". I think we should change this to simply "Enroll Now". Likewise change the copy in the link from "Enroll and Pay Later" to "Audit and Pay Later".
4. Once the Personalized price has been calculated we should no longer display the "Personalized Course Pricing" card. We can just remove it, and display a small message with the cost at the top of the Courses card.

![image](https://cloud.githubusercontent.com/assets/20047260/22113588/c0a4dfec-de34-11e6-87e8-5963668dbace.png)

![image](https://cloud.githubusercontent.com/assets/20047260/22113573/afe9f78c-de34-11e6-9ac7-30cde4510737.png)

**Comment by roberthouse54** [comment]
Closed in favor of #2481: the new issue has the same design but does not include all the back and forth discussion.
