### ISSUE TITLE
force login of users if, when we query edX, we get a 401

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#221]
edX will return a 401 when the user's oAuth token has expired, which will happen more frequently after we change to the new OAuth library.

**Comment by pdpinch** [comment]
Is this addressed by #278 ?

**Comment by pdpinch** [comment]
this is probably already done.

**Comment by pdpinch** [comment]
@giocalitri I'm not sure how to test this. I tried changing my access_token in the user social auths table -- assuming this would cause edX to respond with a 401. When I tried to load the micromasters dashboard, I got a 500 error though. 

I also tried changing the value of updated_at to a time in the distant past. Reloading the dashboard under these condition lead to a refresh of the token information and the dashboard reloaded without error and without requiring another login.

**Comment by giocalitri** [comment]
Probably the only way to test this is to edit, inside the user social auth JSON in micromasters, the refresh token to something else. This will make the refresh token invalid and should force the login.
Now to actually see the login you should probably logout from edx, otherwise without the authorization step you will barely notice the re-login.
Another thug that you can check is that there will be a brand new access token for the same user (instead when the refresh token is used successfully, the same access token is reused and updated)

**Comment by pdpinch** [comment]
Thanks! I tested this and it works. 

1. Using an existing session, I 
2. scrambled the user's refresh token in django-social-auth
3. reloaded the learner dashboard

I got a brief flash of a 401 error on the dashboard and then I was redirected to login with edX. 

Logging in worked as expected.
