### ISSUE TITLE
Text Edits to DEDP MM Page/dashboard

### ISSUE THREAD

**Issue by ChrisLanfranco** [mitodl/micromasters#2298]
I have couple minor adjustments to messaging on the DEDP portal that Maria Cruz has approved. I know that she's been in touch with Anna Schrimpf in regards to making edits. @mariaodl 

See attached doc for edits.
[DEDP Edits.docx](https://github.com/mitodl/micromasters/files/696302/DEDP.Edits.docx)

**Comment by pdpinch** [comment]
Hi Chris. About half of these changes are in pages in the CMS and Anna can change those herself. 

The others are part of the learner dashboard and require a code change. I have some questions about these that we'll have to follow up with Anna & Maria about -- e.g., there's not enough room to replace "enroll and pay later" with "Enroll for free to audit this course. You may upgrade to MicroMasters track later."

I'll update this issue when I find out more. I expect I'll break it into a few separate ones. 

FYI @roberthouse54 @Ferdi

**Comment by ChrisLanfranco** [comment]
Sounds good, I believe I have meeting with Anna & Maria at 1 today if at some point you want to swing by.

**Comment by roberthouse54** [comment]
Here is my feedback on the text edits. Overall, I think these changes look good, but a few comments:

1. I think it is a bit confusing to say "you may take and complete the courses for free. " And then in the next sentence to explain that actually, to earn the credential, you have to pay. Perhaps this can be explained a different way so that it is more clear.

2. "To find out how much you will pay, click here to start this process." - I am guessing that "click here" links to the Sign Up UX. We have discussed adding a sort of pared-down cost calculator to the DEDP marketing page, but we do not have this yet. In the meantime, would it make more sense to say something like "To find out how much you will pay, click here to sign up." (Maybe this is not worded well, but something to that effect.

3. "Enroll for free to audit this course. You may upgrade to MicroMasters track later." - I agree with Peter. This is much too long to fit in this spot in the UI. Also, we are saying basically the same thing just above this section. We should be consistent and use the same terminology in all places in the UI and marketing where we are discussing this option. So maybe instead of "Enroll and Pay Later" it could be "Audit and pay later" or "Audit for free and pay later" (even that is a bit long).

**Comment by pdpinch** [comment]
The last bit of this was closed by #2536
