### ISSUE TITLE
JavaScript error with date picker in FinancialAidCard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2432]
This doesn't happen too frequently, but this feature isn't used that frequently. The issue seems to be limited to Chrome

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190476376/

```
TypeError: Cannot read property 'format' of null
  at onChange (./static/js/components/dashboard/FinancialAidCard.js:94:57)
...
(16 additional frame(s) were not displayed)
```

**Comment by singingwolfboy** [comment]
Looks like the problematic code is here:
```jsx
<DatePicker
  selected={moment(documentSentDate)}
  onChange={(obj) => setDocumentSentDate(obj.format(ISO_8601_FORMAT))}
/>
```

I'm guessing that if the user clicks "submit" while the datepicker is blank, then the `obj` parameter will be `null`. The proper solution here is to validate that the datepicker has a value before submitting. However, this means we need an error state for this form, so that we can indicate to the user that the value is required. This might require a bit of design work.

**Comment by amir-qayyum-khan** [comment]
#### To produce the issues:
On master branch, open browser console and remove date from FA calculator. You will see exception.

<img width="843" alt="screen shot 2017-04-19 at 4 54 27 pm" src="https://cloud.githubusercontent.com/assets/10431250/25178858/fcbbd750-2520-11e7-8fff-21614eecbbce.png">
