### ISSUE TITLE
Dashboard: Don't show missed payment deadline when learner has already passed and paid

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2449]
We've received a couple of tickets from users who have paid and passed for a (verified) course and then enrolled again in a subsequent run of the course. When the upgrade/payment deadline for the later run passes, we display a message on the dashboard that they need to upgrade, even though they passed and paid for the earlier run. 

from [ZenDesk #5286](https://odl.zendesk.com/agent/tickets/5286)

> Steps to reproduce:
> 1. Set up a user who has paid for and passed a run of a course in the past
> 2. Enroll the user in a more recent run of the course, with a upgrade deadline in the past
>
> Expected Behavior
> Uncertain, but the dashboard should make it clear that the user has passed the course and need not take it again.
>
> Actual Behavior
> The top line run for the course indicates that the user missed the upgrade deadline and won't get credit. Below that, we provide a link for the user to enroll or pay in the next run of the course. And below that we display the course run where the user passed.

**Comment by pdpinch** [comment]
@roberthouse54 did you say you had some thoughts on how to resolve this issue?

**Comment by roberthouse54** [comment]
Yes. I think we should show a status message saying that the user has already paid for the course, and does not need to pay because they already have credit towards the MicroMasters credential. We will also say that they can still pay again if they want to. (Wording to be figured out). Then we can have a link that says "Pay for this Course", but this will be a smaller less prominent link. We will not show the missed deadline status message in this use case. 

Since this is a lot to explain, I would prefer that we wait until we have updated the layout of the Course status to the new 2-column design. The status message would show up in the usual place.

I will mock this up today to show you what I mean.

**Comment by pdpinch** [comment]
@roberthouse54 Is this already included in #2563 or does it need additional design?

**Comment by roberthouse54** [comment]
It is included in #2563. This is called "Auditing, but passed a previous course run"

**Comment by pdpinch** [comment]
This should be addressed by #3046

**Comment by pdpinch** [comment]
This was closed by #3046
