### ISSUE TITLE
Add eslint rule to require spaces surrounding infix operators

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2471]
http://eslint.org/docs/rules/space-infix-ops

**Comment by noisecapella** [comment]
Also this one: http://eslint.org/docs/rules/space-before-blocks

**Comment by aliceriot** [comment]
I support this plan

**Comment by noisecapella** [comment]
I'm also thinking of adding [space-in-parens](http://eslint.org/docs/rules/space-in-parens) which would forbid `if ( x === undefined )` in favor of `if (x === undefined)`. @aliceriot what do you think?

**Comment by aliceriot** [comment]
hum that's a tricky one, I happen to like a little bit of space in my parents. I'm definitely more into:

```js
if ( foo.isFoo() ) {
  ...
}
```

than

```js
if (foo.isFoo()) {
  ...
}
```

mainly just because I think lots of parentheses ends up looking crunched up.

then again, I also prefer `{ foo: 'bar' }` to `{foo: 'bar'}`, so maybe I'm just a radical, pro-whitespace element :D

**Comment by noisecapella** [comment]
Haha I'll leave that rule out then

**Comment by aliceriot** [comment]
then again [JavaScript standard style](https://github.com/feross/standard) turns on the `space-in-parens` rule, so...maybe it's fine, haha.

**Comment by noisecapella** [comment]
Alright, I'll add it back. Mostly I'm looking to prevent things like

    if ( func(does(stuff))) {
      ...

**Comment by aliceriot** [comment]
Yeah, that's yucky all over
