### ISSUE TITLE
Search: Current Residence needs the "more"

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#2514]
In case there are too many results, the list becomes really long

![screen shot 2017-02-07 at 11 02 44 am](https://cloud.githubusercontent.com/assets/1005204/22699289/0f20ffc6-ed25-11e6-9bad-ce463131f397.png)

**Comment by pdpinch** [comment]
@roberthouse54 what would you like to do with this?

I think Giovanni's just suggesting cutting the list off at a fixed number and adding a more link. I'm not sure this will work, but it seems like it should. 

I don't think we can do the same UI as company, because current residence consists of hierarchical facets. 

We can also collapse the entire facet by default and wait for the user to twiddle the disclosure triangle.

**Comment by roberthouse54** [comment]
I think we should cut off the list at 15, and have a View More link, so that will be consistent with the Country of birth facet.

**Comment by aliceriot** [comment]
I think there was an issue before for this (https://github.com/mitodl/micromasters/issues/2038). The hierarchical menu component does not support the `size` prop (which can be used to get a 'more' link more or less for free) out of the box, so we'd need to either open a PR against Searchkit to add this behavior or patch the searchkit component ourselves (probably neither of these are trivial).

this is also a dup of https://github.com/mitodl/micromasters/issues/2155

**Comment by pdpinch** [comment]
Thanks @aliceriot.

Closing in favor of #2155 which links to the gory history.
