### ISSUE TITLE
Search: include username and e-mail address in name search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2668]
#2479 added a search box to the search page that allowed for filtering by leaners' names. Course teams have pointed out that on edX they don't have (easy) access to learners' names, but they do have access to username and e-mail addresses (the former on the discussion board, the latter if the user contacts them by e-mail). 

It would be helpful if the search box could filter by username and e-mail in addition to first name, last name, etc.

**Comment by pdpinch** [comment]
The UX may be less than idea since those fields don't appear in the search results and thus the text can't be highlighted. But we shouldn't block the functionality due to that issue. 

@roberthouse54 any thoughts on this?

**Comment by roberthouse54** [comment]
I don't really want to add both email and username to the results list because I think it will be getting too cluttered. Can we add just the username (see below)? We can still match on email, and just not display the email in the table. We are already displaying the preferred name in parenthesis next to the name.

![image](https://cloud.githubusercontent.com/assets/20047260/23219240/88ab797a-f8ec-11e6-8568-bea1903faae4.png)
