### ISSUE TITLE
Name search in learners search does not work with full name

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2742]
It does a prefix match on first, last, or preferred name (and soon the username and email), but it does not do full name searches. Not sure if this is a bug or feature request

**Comment by pdpinch** [comment]
For example, if you search for the fake user "Xavier Addy" -- i.e. `/learners/?q=Xavier%20Addy` -- you will get no results. But if you search for "Xavier" or "Addy" you will find him.

**Comment by singingwolfboy** [comment]
We can reconfigure the way Searchkit queries the backend to make it return results that are a perfect name match. For example, for a user "John Smith", we could modify the query parameters so that Elasticsearch knows to return that user for the search string "John Smith". However, we can't currently do a prefix match for both first name and last name: the search string "John Smi" would not return the user.

To support prefix matches for both first name and last name, we'll need to add a `full_name` field to the Elasticsearch index. We could do that with an [ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/ingest.html), but we need to upgrade to Elasticsearch 5 before we can use that feature. (#2867).

We might be able to do add a `full_name` field to the Elasticsearch index by changing how Python serializes Profile objects before sending them off to Elasticsearch.

**Comment by singingwolfboy** [comment]
Correction: we can't make Searchkit send queries that will _simultaneously_ return a perfect name match _and_ a prefix match. In order to do that, we still need a `full_name` field.
