### ISSUE TITLE
exams: create models for storing exam results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2790]
Part of #2752 

We need a model for storing exam results. 

The results will be displayed to users in their dashboard, and also used to calculate their final grade for the course. 

### acceptance criteria
- [ ] audit tables
- [ ] simple admin interface that allows for looking up exam grades, and allows editing

**Comment by giocalitri** [comment]
After talking with @rhysyngsun I realized that this model should contain only the data we need to expose (probably only grade and whether the user passed the exam) and dump the rest in a JSON field.
My question is: is that all we need?

**Comment by rhysyngsun** [comment]
@giocalitri @pdpinch one question I raised at some point (no clue where it lives among the plethora of exam tickets) was that the data we get back does not seem to indicate the maximum score for an exam which we would need in order to compute a percentage score. Assuming we don't (and can't) get that from their results files we probably need to figure out where to store that too (I would not assume the maximum score is fixed). This might touch on the issue of tracking "exam runs" that we've toyed with doing as well...

**Comment by giocalitri** [comment]
oh, I had not realized that. I just saw the "passing score" field that can be used to compute if the user actually passed the exam (even if the explanation is a bit cryptic)

**Comment by rhysyngsun** [comment]
Yeah I think we need it for #2915
