### ISSUE TITLE
exams: process exam results files from Pearson

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2791]
Exam results from Pearson arrive in files from sftp (first expected on 3/21/17). These files need to be parsed and the data saved, to the model created in #2790 

### acceptance criteria
- [x] save the file to long-term location, like an encrypted S3 bucket (#2896)
- [ ] log and raise and errors (parsing errors or errors found in the file)

**Comment by rhysyngsun** [comment]
@pdpinch some questions/thoughts based on reading docs:

- It looks like we only get data for the learner's grade and the passing grade for an exam. For example, a passing grade might be 400 and the learner got a 450, but we won't know from response data what the highest possible grade was so we need to store that somewhere. My question is: do the maximum exam grades differ between courses?
- What do we want to do with incomplete, unfinished, and refused statuses (there's also a "taken" status, but that is for exams with no grade).
- There's a lot of potentially valuable data around the exam in the response files that we might want to use down the road and since we can't simply make an API request to get this data I'd advocate persisting all this in an intermediate data model that we can then compute a final exam grade from.

**Comment by rhysyngsun** [comment]
@pdpinch there's still two outstanding questions above but this is otherwise blocked by #2896, which I need to discuss with Ops on the approach.

**Comment by pdpinch** [comment]
- I've send an e-mail to DEDP re: "incomplete, unfinished, and refused statuses"
- We should preserve the files with all the question/answer data. DEDP may want to analyze that, but I doubt we'll do anything with the MM app with it directly.

**Comment by pdpinch** [comment]
We've confirmed with Pearson that those exam statuses other than `Pass` and `Fail` should never occur for our exams. If they do, we can log them as exceptions, but we don't need any logic currently for parsing them.
