### ISSUE TITLE
clicking on user's name returns user to dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#292]
For logged in users, we display their name and a drop-down menu in the top right corner. Clicking on the users name should return her to the dashboard. 

This would replace the "Dashboard" link in the top nav

- [ ] add link to user name, for logged in user 
- [ ] remove "Dashboard" link from top nav

**Comment by amir-qayyum-khan** [comment]
@pdpinch you are saying instead of ```dashboard``` link on landing page add ```user name link```

<img width="656" alt="screen shot 2016-05-09 at 6 26 58 pm" src="https://cloud.githubusercontent.com/assets/10431250/15114525/d9803d0c-1613-11e6-95ff-749db718a035.png">

And remove this dashboard link at all from ```dashboard page``` . Am I right?

<img width="650" alt="screen shot 2016-05-09 at 6 27 20 pm" src="https://cloud.githubusercontent.com/assets/10431250/15114556/f598746e-1613-11e6-816b-4a6f31541e58.png">

**Comment by pdpinch** [comment]
It's hard for me to say for sure without the URLs, but I tried to clarify the description. Note that this is only relevant to the logged-in user.

**Comment by amir-qayyum-khan** [comment]
Done with changes in PR #300
<img width="639" alt="screen shot 2016-05-10 at 7 01 10 pm" src="https://cloud.githubusercontent.com/assets/10431250/15149223/1ea6e178-16e2-11e6-8fe4-beeed8082f37.png">
