### ISSUE TITLE
404 page as a logged in learner viewing a public_to_mm profile

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2947]
- Log in as a learner (no staff permissions)
- View another learner's profile that has `account_privacy` set to `Profile.PUBLIC_TO_MM`

Expected result: user can see the profile
Actual result: 404 page

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
This is because your user is not a `Verified micromaster user` and we dont show `PUBLIC_TO_MM` profiles to users who are not verified. please see https://github.com/mitodl/micromasters/blob/master/profiles/permissions.py#L64

#### And setting i am talking about is
<img width="622" alt="screen shot 2017-04-24 at 5 33 59 pm" src="https://cloud.githubusercontent.com/assets/10431250/25337242/8a2e2146-2914-11e7-8e69-723e86429d67.png">

**Comment by amir-qayyum-khan** [comment]
fixed by #3102
