### ISSUE TITLE
Dashboard: Course run and status messages UI

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3048]
This ticket has two parts: a) In Progress course run layout, and b) status messages. (NOTE: "Grades" are addressed in #2792)

![image](https://cloud.githubusercontent.com/assets/20047260/25249908/a44aa18e-25e1-11e7-8fc1-73f23e9becf5.png)

**In Progress edX Course**

Once a user is enrolled in a course run, display the in progress course run layout:

- If course has not started: "Course starts [date]"
- If course start date is <10 days: "Course starts in [x] days"
- If course has started: "Course in progress"
- Links to "View course on edX" and "Contact course team" - no change in functionality.
- edX "Progress" with a percentage and a progress bar.
- Once a course run has been completed, hide this section. If the course run was completed, show the grade in the grade box.

**Status Messages**

- Statuses are displayed in a gray box at the bottom of the course layout. This can be any kind of status message. Some statuses include buttons. Buttons appear to the right of the text, aligned right.
- If there are secondary calls-to-action, these will be displayed as links, not buttons.
- A course can (rarely) display more than one status message at the same time. In this case, just stack them vertically, with a margin between.

## List of Statuses below

**Auditing**
- Shown when a user is enrolled in a course but not paid.
- Button: Pay Now
- Copy: You are auditing. To get credit, you need to pay for the course.

**Run Complete (DEDP)**
- Button: Re-enroll (Show Course start date next to button)
- Copy: The edX course is complete, but you need to pass the final exam. If you want to re-take the course you can re-enroll [link].
![image](https://cloud.githubusercontent.com/assets/20047260/25350601/ac1fcf5a-28f3-11e7-8a46-1ae7a52e1dd7.png)

- Clicking the "re-enroll" link will display the next upcoming run below the status message, as shown below. 
![image](https://cloud.githubusercontent.com/assets/20047260/25350708/0ab35032-28f4-11e7-8017-5164cdfdeaeb.png)

**Run Complete (DEDP) - Not yet paid**
- Button: Pay Now
- Copy: The edX course is complete, but you need to pass the exam. (Payment due on [date].)
![image](https://cloud.githubusercontent.com/assets/20047260/25350757/2bf29334-28f4-11e7-886e-bfd52c757993.png)

Run Not Passed
- This status is shown any time a course has ended and the user has not passed. This includes both students who took a course and did not receive a passing grade, and students who audited.
- Button: Re-enroll 
- Copy: You did not pass the edX course, but you can re-enroll. 
Next course starts 9/10/2017 
![image](https://cloud.githubusercontent.com/assets/20047260/25350817/605b120e-28f4-11e7-8575-085c63b081cb.png)

Passed Course
- this shows when a user has passed the Course. For DEDP, this means that the user has passed both the course run AND the exam. For programs that do not require an exam, this means the user has passed the edX course.
- Button: View Certificate
- Button: Re-enroll 
- Copy: You passed this course.
![image](https://cloud.githubusercontent.com/assets/20047260/25350877/9c39194c-28f4-11e7-80a7-6b4a7d8d764b.png)

Missed Payment Deadline
- This shows when a user has missed the payment deadline for a course.
- Button: Re-enroll (Show Course start date next to button. If enrollment is not open, also show enrollment start date.)
- Copy: You missed the payment deadline, but you can re-enroll.  
Next course starts 9/10/2017 
![image](https://cloud.githubusercontent.com/assets/20047260/25350847/80f7f7a2-28f4-11e7-93db-6a66f3161100.png)
 

Auditing but previously paid
- Button: Pay Now
- Copy: You are auditing, but you do not have to pay for this course again because you already completed it. If you want,t you can pay for the course.

![image](https://cloud.githubusercontent.com/assets/20047260/25350943/d9c61792-28f4-11e7-8846-8f4f54060281.png)

Error state
- Copy: Something went wrong. You paid for this course but are not currently enrolled. Contact us for help.
![image](https://cloud.githubusercontent.com/assets/20047260/25350979/fac0bcb8-28f4-11e7-8420-cca96a0d198f.png)

Coupon
- Copy: You have a coupon for **$100 off** the price of this course.

**Comment by aliceriot** [comment]
this is just some scratch work to help me make sure I'm covering all of the possibilities, feel free to ignore :)

# List of possible statuses

## In-progress statuses

**[1] Auditing**
- Shown when a user is enrolled in a course but not paid.
- Button: Pay Now
- Copy: You are auditing. To get credit, you need to pay for the course.

![auditing](https://cloud.githubusercontent.com/assets/6207644/25760930/efe111fc-31a6-11e7-8ff4-27f92462a8ea.png)

**[2] Auditing already paid**
- shown when a user is enrolled in a course but has paid for a previous run
- Button: Pay Now
- Copy: You are auditing, but you do not have to pay for this course again because you already completed it. If you want,t you can pay for the course.

![image](https://cloud.githubusercontent.com/assets/20047260/25350943/d9c61792-28f4-11e7-8846-8f4f54060281.png)

## Run completed statuses

**[3] Run Not Passed**
- This status is shown _any time a course run has ended and the user has not passed_. This includes both students who took a course and did not receive a passing grade, and students who audited.
- Button: Re-enroll 
- Copy: You did not pass the edX course, but you can re-enroll. Next course starts 9/10/2017 

![image](https://cloud.githubusercontent.com/assets/20047260/25350817/605b120e-28f4-11e7-8575-085c63b081cb.png)

### Unpaid statuses

**[4] Not paid, deadline not passed**
- this status is shown when the user passed a course but did not yet pay for it, and the deadline has not passed.

**[5] Missed Payment Deadline**
- This is shown when a user has missed the payment deadline for a course.
- Button: Re-enroll (Show Course start date next to button. If enrollment is not open, also show enrollment start date.)
- Copy: You missed the payment deadline, but you can re-enroll.  
Next course starts 9/10/2017 
![image](https://cloud.githubusercontent.com/assets/20047260/25350847/80f7f7a2-28f4-11e7-93db-6a66f3161100.png)

**[6] Unpaid, need to pass exam**
- Button: Pay Now
- Copy: The edX course is complete, but you need to pass the exam. (Payment due on [date].)
![image](https://cloud.githubusercontent.com/assets/20047260/25350757/2bf29334-28f4-11e7-886e-bfd52c757993.png)

### Paid course statuses

**[7] Passed Course**
- this shows when a user has totally passed the Course. If a program requires exams, this means passing the exam and the edX course, and for programs that do not require an exam, this means the user has passed the edX course.
- Button: View Certificate
- Button: Re-enroll 
- Copy: You passed this course.
![image](https://cloud.githubusercontent.com/assets/20047260/25350877/9c39194c-28f4-11e7-80a7-6b4a7d8d764b.png)

**[8] edX course passed, need exam**
- Button: Re-enroll (Show Course start date next to button)
- Copy: The edX course is complete, but you need to pass the final exam. If you want to re-take the course you can re-enroll [link].
![image](https://cloud.githubusercontent.com/assets/20047260/25350601/ac1fcf5a-28f3-11e7-8a46-1ae7a52e1dd7.png)

- Clicking the "re-enroll" link will display the next upcoming run below the status message, as shown below. 
![image](https://cloud.githubusercontent.com/assets/20047260/25350708/0ab35032-28f4-11e7-8017-5164cdfdeaeb.png)

## Other

**[9] Error state**
- Copy: Something went wrong. You paid for this course but are not currently enrolled. Contact us for help.
![image](https://cloud.githubusercontent.com/assets/20047260/25350979/fac0bcb8-28f4-11e7-8420-cca96a0d198f.png)

**[10] Coupon**
- Copy: You have a coupon for **$100 off** the price of this course.

**Comment by aliceriot** [comment]
@roberthouse54 I was working through all the different possible options here as I'm starting to work on this bit of the UI. I don't think we have a mockup for message 4 (above), which would appear when the user passed the course, has not paid, and has not yet passed the payment deadline. Do you have any ideas about what do show for that? I put up my best guess.

**Comment by roberthouse54** [comment]
For number 2, I think we are going to simplify the copy for this status to read only: "You are auditing this course." If the user wants to pay for the course for whatever reason (an edge case) they can go to edX and pay there.

There are also two additional statuses that I forgot:

a. User has passed the edX course, and taken the DEDP Exam but failed. In this case the user can retake the exam one time, at no extra cost. The copy in this case would be: "You did not pass the proctored exam. You can retake the exam by clicking the Pearson VUE link above." (Final copy is TBD, but it will be something like this..)
b. User has failed the Pearson exam twice. We are going to contact DEDP to verify what they want to allow in this case.

**Comment by aliceriot** [comment]
Since I'm currently working on implementing this, would it be alright if, in both of those cases, we showed message no. 8? Just because I'm currently working on it, so it would be good to have something fairly locked-down that I know I won't have to change tomorrow.

**Comment by roberthouse54** [comment]
I feel that it would be good if the status at least tells the user that he/she did not pass the exam. I think @pdpinch  might want to weigh in on this, but it is maybe possible we should not let the lack of clarity about this use case hold up merging the issue as it is currently scoped (??)
