### ISSUE TITLE
add links to 'paid' course status

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#3233]
We want to show the user a link to their certificate on edx and the option to re-enroll, like so:

![paid](https://cloud.githubusercontent.com/assets/6207644/26414872/7d606eca-407e-11e7-80d2-a5cff9fea656.png)

In order to do so we need to add the certificates that the user has earned to the dashboard API so that we can get the certificate URLs cleanly (as far as I know there is not a programmatic way to generate them with the course key or something similar).

**Comment by aliceriot** [comment]
this is part of #3048 which will be worked on immediately after it merges.

**Comment by pdpinch** [comment]
@annagav this issue is slightly larger in scope that what I asked you to work on, so we can take this in two pieces:

1. [ ] Display link to certificates hosted on the MM portal (FA courses)
2. [ ] Display link to non-FA certificates hosted on edx.org (non-FA courses)

Presumably, everything in category 1) will have an entry in the certificates table.

For category 2) I think you'll find a link in the CachedCertificate model

**Comment by pdpinch** [comment]
Anna, will #3500 fix this when it merges?

**Comment by pdpinch** [comment]
@annagav Can we close this?

**Comment by annagav** [comment]
I don't think the `re-enroll` part of it was implemented.

**Comment by pdpinch** [comment]
I opened a new issue for the re-enroll button. We can close this.
