### ISSUE TITLE
As superuser (staff?) I want to see the student's dashboard in the same way the student sees it

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#3329]
This would be really useful to debug problems in production.

**Comment by pdpinch** [comment]
Can we do this using django-hijack like we did [on OVS](https://github.com/mitodl/odl-video-service/pull/599)?

**Comment by pdpinch** [comment]
@amir-qayyum-khan when I try this on -rc or in production, I get a 401 error from /dashboard and then I am redirected back to my own dashboard. 

The 401 error makes me wonder if the dashboard update is failing because the wrong oAuth token is being used. 

FWIW, I don't have this problem on bootcamps, which has a similar log in mechanism (but no dashboard update).

**Comment by pdpinch** [comment]
I'm not sure what changed, but this seems to be working OK now on production. 

It may be that if the user doesn't have a complete profile yet, the profile validation interferes with the hijack.

**Comment by amir-qayyum-khan** [comment]
awesome, it was working fine on MM today i was testing it.
