### ISSUE TITLE
Display payment deadline on dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3516]
The customer support team is getting a lot of questions about the specific day and time when payment is due. It would help them if this information was displayed -- on the dashboard and/or the program page. 

See [ZenDesk #10860](https://odl.zendesk.com/agent/tickets/10860)

**Comment by roberthouse54** [comment]
We already display the Payment deadline in 2 cases... 1) if the edx course is complete but the user still need to pay to get credit, or 2) in the case of DEDP, the edx course is complete and the user needs to pay in order to take the exam.

So the only change we need is to add the Payment deadline info on the auditing status while the course is in progress. This message will say:

You are auditing. To get credit, you need to pay for the course.
(Payment due 9/10/2016 at 3 PM UTC)

NOTE: We should also add the UTC time to the other 2 statuses mentioned above.

![image](https://user-images.githubusercontent.com/20047260/30978802-a386a1da-a449-11e7-8219-39d01ff77f6f.png)
