### ISSUE TITLE
add wizard / progress UI to profile / enrollment forms

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#369]
Instead of tabs, the profile / enrollment forms should have an indicator so users know which step they are on. 

There are no links to jump between forms. The only way to advance is to click the "save and continue" button. (we need to add a "Previous Step" button but there's no design yet)

Here is the most recent design:
![step two - alt wizard 2](https://cloud.githubusercontent.com/assets/430126/15434412/afa501ce-1e84-11e6-8f40-2a23bf0a4a3e.png)

**Comment by noisecapella** [comment]
@gsidebo FYI this will need tests too, similar to existing tests for `makeCourseProgressDisplay`

**Comment by noisecapella** [comment]
It seems like we should remove the react-router handling for the tabs as well, so the user can't just go to /profile/education in the browser as a workaround. What do you think @aliceriot?

**Comment by aliceriot** [comment]
hmm that might be what we want but I think that will entail a decent refactor of how the `ProfilePage` component injects props into the tab components - we might need a dummy component that just renders:

```js
<ProfilePage>
  <EmploymentTab />
</ProfilePage>
```

to keep the existing pattern. Either way I think this is blocked until https://github.com/mitodl/micromasters/issues/375 and https://github.com/mitodl/micromasters/issues/393 are merged, the former because we need the 'back' button and the latter because it entails a major refactor of related classes anyway (`ProfilePage`, mainly).

**Comment by noisecapella** [comment]
Ok, I'll work on removing the links but otherwise not touch the react-router pieces. I'll file a new issue to cover the removal of the react-router support for individual profile pages

**Comment by aliceriot** [comment]
I do agree that it doesn't necessarily make sense to have the user able to navigate around by URL, but at the same time with the `requireProfileFilledOut` and `requireCompleteProfile` methods on `App.js` we might have those edge cases covered anyway - meaning, it shouldn't be possible for a user to do any interaction with the site until they've filled out the profile, so someone editing the url to skip ahead to e.g. `/profile/professional` and skip the education form might not be a problem (since they'll be redirected to the education tab as soon as they click 'I'm done' on the privacy tab).

**Comment by noisecapella** [comment]
At the moment we don't actually validate that the user has to enter any work history or education, even if the switches are enabled indicating they had something to add... but when we fix that it should work like you said

**Comment by aliceriot** [comment]
ah
right yeah, for the work history validation if `profile.work_history` is an empty array we don't validate it.
