### ISSUE TITLE
Upgrade to elasticsearch 6

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3748]
We should do #2867 first, I'm not sure if skipping major versions is a good idea

**Comment by blarghmatey** [comment]
The version that we are currently running was EOL last month so we should work on this upgrade as we are able to.

**Comment by rhysyngsun** [comment]
The changes are getting reverted in #4319 due to the upgrade path being more complicated (see #4318).

**Comment by tasawernawaz** [comment]
@rhysyngsun anything I can do on this ? or is this waiting on Devops ?

**Comment by rhysyngsun** [comment]
@tasawernawaz someone needs to determine what the proper steps/order are for upgrading the cluster and the django dependencies in a way that won't break functionality, I think as we last left it, it should be one of us who looks into this instead of devops since it comes down to what the application needs in terms of compatibility at the different stages and how we would need to step through the migration as far as application code. That probably means this needs to become an epic with child issues for both the application and devops that need to be done in a precise order.

**Comment by blarghmatey** [comment]
I think the easiest first step is to determine whether the code changes can be put behind a feature flag which we can flip once we get the infrastructure in place

**Comment by blarghmatey** [comment]
@markbreedlove for this we need to do a few stages of rollout. First is to synchronize the data in the existing Elasticsearch indices for micromasters production to the cluster running in the production-apps environment, followed by validating that the app can connect to the other cluster, and then running a reindex after the cutover.

There are some other details to be considered, but that is the broad context.
