### ISSUE TITLE
Link to mail settings in mail footer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3806]
All the outgoing mail from MicroMasters should include a footer with a link to the mail settings page, so learners can easily unsubscribe.  

### out of scope
- it would be nice if the mail settings page could be accessed without requiring login. We can implement this after we do it for discussions, https://github.com/mitodl/open-discussions/issues/463

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/35925756-88da4bee-0bf4-11e8-8de2-9403daedaf23.png)

Note that we will need different versions for MicroMasters emails, vs Open Discussions emails, as the copy will be slightly different and the links go to different places. 

For MicroMasters emails:
"You are receiving this e-mail because you signed up for MITx MicroMasters. If you don't want to receive these emails in the future, you can edit your settings or unsubscribe."

For Open Discussions emails:
"You are receiving this e-mail from MIT Open Discussions because you signed up for MITx MicroMasters. If you don't want to receive these emails in the future, you can edit your settings or unsubscribe."

Both "settings" and "unsubscribe" link to the same place.

**Comment by pdpinch** [comment]
@annagav we're missing the postal address. I know it's weird, but I understand that its required.
