### ISSUE TITLE
Misleading semester enrolled search results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3840]
Related to #3810 

The way enrollments are serialized here only the first found paid course run enrollment is serialized and indexed, and that is the course run grade and semester that will show up in the search results.

**Comment by pdpinch** [comment]
@annagav is this still an issue? it seems like `serialize_enrollments()` gets *all* the course runs? 

https://github.com/mitodl/micromasters/blob/63b9f4bc1379b599ed3b8d857ec67d97c49136a3/dashboard/serializers.py#L17-L34

**Comment by pdpinch** [comment]
oh... using `course_title` as a key isn't reliable.... Sometimes the course titles change from run to run. I'm pretty sure that happens with 14.73x. 

So what do we need to do to capture all the course runs, use a different index for this serialized_enrollments_map? How about `edx_course_key` or even just `course_run.id` or `course_run`?

**Comment by annagav** [comment]
I think the reason to serializing one course run per course here is that we were getting wrong results in the enrollment numbers in the courses facet, because we want the number of users enrolled in the course. Before this change we were getting the number of all enrollments, and same user could be enrolled in same course multiple times in different course runs.

**Comment by pdpinch** [comment]
Hm. Would it make sense to serialize the course and the courseruns separately?

**Comment by annagav** [comment]
Yes, I think we need to serialize the semester enrolled separately.
