### ISSUE TITLE
Search: Discrepancies in results compared to Postgres

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3964]
We have noticed some discrepancies in comparing the results of learner search to a SQL query of Postgres data. 

- [ ] Learners who have unenrolled from courses in edX aren't being removed from the search index
- [ ] other issues

**Comment by maxliu** [comment]
Related queries on redash BI.
1) Elastic search, learners from 2016 - fall.  https://bi.odl.mit.edu/queries/329/source#531 This results match the one we got from MM portal ( 985 as 04/24/2018).
2) MM Postgre, learners from 3T2016. https://bi.odl.mit.edu/queries/330/source The count of unique users is 1860 ( as 04/24/2018).

A data file in Excel format is also available. It can be shared with team member on Keybase drive.

So far there are two reasons discovered. use 2016 - fall as an example.

**Comment by maxliu** [comment]
One more example. Data from POM 1T2018
ES : https://bi.odl.mit.edu/queries/337
Postgres: https://bi.odl.mit.edu/queries/336

**Comment by maxliu** [comment]
Good catch!

Here is new summary of  POM 1T2018 data.

Count   of username |   | in_ES |  
-- | -- | -- | --
filled_out | in_ProgEnr | 0 | 1
0 | 0 | 110 |  
  | 1 | 5 |  
1 | 0 | 259 |  
  | 1 |   | 175

Now we can explain why some users are in MM database but not ES (for POM 1T2018). 115 of them haven't fill out the profile (filled_out=0). 259 of them are not in "dashboard_programenrollment".

**Comment by pdpinch** [comment]
Can you rerun your analysis of the DEDP 3T2016 data with the updated program enrollment constraint?

**Comment by maxliu** [comment]
New data summary for DEDP 3T2016


Count of user_id |   | in_ES |  
-- | -- | -- | --
filled_out | in_ProgEnr | 0 | 1
0 | 0 | 411 |  
0 | 1 | 77 |  
1 | 0 | 51 |  
1 | 1 | 402 (cant explain) | 922

**Comment by maxliu** [comment]
Notes:

ES for DEDP 2T2017 https://bi.odl.mit.edu/queries/348/source
Postgres for DEDP 2T2017 https://bi.odl.mit.edu/queries/349/source

**Comment by maxliu** [comment]
By investigating the data above, the discrepancies  between ES and MM database are caused by two reasons.

1. For users who deactivated on eDx, ES still keep them but the records won't be in MM database.
2. For users who enrolled multiple times for the same course (different course run), ES only report one of them but MM database will keep all the records.

**Comment by maxliu** [comment]
@pdpinch #3840 will only solve the second issue. we might need start a new issue for the first issue - remove the deactivated users from ES.

**Comment by maxliu** [comment]
@pdpinch just shared a excel file for the list of users who in ES but not in postgresql. they all are not active in edx. dedp_2T2017_in_es_notin_pg.xlsx

**Comment by pdpinch** [comment]
@maxliu what's the status of this issue?

**Comment by maxliu** [comment]
1. Learners who are in Pg but not in ES. See data file dedp_2T2017_07_17_2018_in_pg_not_in_es.xlsx. There are 1015 learners for DEDP 2T2017 semester.  Reasons are : 

-  “Is_active” = 0
-  “Is_staff” = 1
-  “In_program” = 0
-  “Profile_filled_out” =0

2. Learners who are in ES but not in PG. See data file dedp_2T2017_in_es_not_in_pg_07_17_2018.xlsx.  There are 250 records for DEDP 2T2017 semester. This is because those learners are not active (“is_active” = 0) on edX anymore, so that MicroMaster database won’t collect info for those learners. However, ES won’t delete the records.

**Comment by pdpinch** [comment]
What's the definition of `is_active` on edX? Are there any specifics in the edX analytics documentation?

**Comment by pdpinch** [comment]
replaced by #4066
