### ISSUE TITLE
next parameter doesn't work if user already logged in

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4190]
### steps to reproduce
1. Log out of discussions, micromasters, and edx
2. navigate to `/login/edxorg/?next=/discussions/` in micromasters
3. entering credentials in edx
  you should be redirected to discussions (via micromasters)
4. Now, with active logged-in sessions, navigate _again_ to  `/login/edxorg/?next=/discussions/` in micromasters

### expected behavior
- redirected to discussions (same as the result of step 3 above)

### actual behavior
- redirected to your dashboard on micromasters (`/dashboard` for learners and `/learners` for staff)

It appears the `?next=` parameter is being ignored.

**Comment by rhysyngsun** [comment]
@pdpinch my guess is this is a behavior of python social auth not using the `next` parameter when the user is already logged in, since social auth is the piece that does that redirecting. Someone will need to debug through social auth to figure out why the param is not being used.

**Comment by rhysyngsun** [comment]
The code that stores and consumes that parameter is [here](https://github.com/python-social-auth/social-core/blob/1d809941ab8a99af9e1bdf12bae548202c94eaa2/social_core/actions.py)

**Comment by tasawernawaz** [comment]
@rhysyngsun I have debugged the [method](https://github.com/python-social-auth/social-core/blob/master/social_core/actions.py#L7) you suggested, whenever we hit this method it has correct value of next. i.e
`data = <QueryDict: {'next': ['/discussions/']}>`
which is used to make redirect_uri. So I don't think problem is with this method.

I have also opened an [issue](https://github.com/python-social-auth/social-core/issues/316) on social-core, may be we can get any help from there.
FYI @pdpinch

**Comment by pdpinch** [comment]
Can you add some details on what you found in debugging. 

1. Were you able to reproduce the issue?

2. Can you determine where in the flow the parameter is getting lost?

**Comment by tasawernawaz** [comment]
@pdpinch I am able to reproduce this, however as suggested by @rhysyngsun I believe this issue is not part of our code. I haven't found any issue in [`do_auth()`](https://github.com/python-social-auth/social-core/blob/master/social_core/actions.py#L7) method wither. I will keep investigating on this.

**Comment by rhysyngsun** [comment]
@pdpinch @tasawernawaz I don't think we should expect a timely upstream fix (or one at all if this is intended behavior). An alternative approach would be to revert the production configuration change and start sending users back to `/discussions` again and make sure that endpoint redirects the user appropriately. At some point we changed this to `/login/edxorg/` because we wanted the users to just login and not get the prompt.

There are two ways to do this:

- Update `LOGIN_URL` in settings.py to `/login/edxorg/` so that any `@login_required` decorators redirect to there. Current behavior is to redirect to `/` and have the signup prompt display. This is the more impacting choice and might break other things
- Update the redirect *only* for `/discussions` by specifying `@login_required(login_url="/login/edxorg/")`, this achieves the desired behavior for a MM->Open login without impacting any other routes.

**Comment by tasawernawaz** [comment]
@pdpinch Could you also give your opinion before moving forward.

@rhysyngsun thank you for your input here. 
> * Update the redirect _only_ for `/discussions` by specifying `@login_required(login_url="/login/edxorg/")`, this achieves the desired behavior for a MM->Open login without impacting any other routes.

I think we are not using login_required decorator as most part of the code is react based.

**Comment by tasawernawaz** [comment]
@rhysyngsun I have tested second option from your suggestions, but it isn't working. Am I missing something ? Here is the link of my PR #4253
