### ISSUE TITLE
Clean up util/util.js

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#438]
There's a lot of functions there, we should move them into separate files. We should also refactor some functions which return react components into their own react components.

**Comment by aliceriot** [comment]
@noisecapella picking this up since my stories are both out for review.

I'm thinking of:

- [ ] moving validation-related functions out of `util.js` and into `validation.js`, so they're all in one place (and moving the tests for those same functions to `validation_test.js`)
- [ ] moving the course progress display related functions into a new file (maybe `util/courseProgress.js` or something similar)

thoughts?

**Comment by noisecapella** [comment]
Sounds good to me. The course progress functions all return some sort of `ReactElement` so maybe `util/ui.js` would fit better there?

**Comment by aliceriot** [comment]
that makes sense to me!

**Comment by noisecapella** [comment]
Actually I've been wondering if those UI functions should just be made into components and moved into their own classes... up to you! No strong opinions here

**Comment by aliceriot** [comment]
hmm, I'll play around with it!

**Comment by gsidebo** [comment]
> The course progress functions all return some sort of ReactElement so maybe util/ui.js would fit better there?

i'm wondering why these things exist in a directory called "util" at all. a lot of these don't strike me as utility functions. as for these UI components, why not something like "static/js/components/common"? or maybe "shared" instead of "common"?
