### ISSUE TITLE
Mailing list form on home page should behave the same as form on current site

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#472]
- [x] default state: comments field and Institution name field are hidden
- [x] when the user selects "I represent an interested corporation" or "I represent an interested university or educational institution" the "institution name" field is displayed
- [x] when the user selects "Other" the "comments" field is displayed
- [x] when the user selects "I am an interested learner" the form reverts to its default state

**Comment by pdpinch** [comment]
@amir-qayyum-khan I thought this was going to be part of #287. Is this a bug, or did you just leave it out?

**Comment by amir-qayyum-khan** [comment]
ops, that was not assigned to me, i havent seen this at all. By the way is is already fixed in #287.

**Comment by amir-qayyum-khan** [comment]
Fixed via #287.

**Comment by pdpinch** [comment]
This isn't displaying properly for me on micromasters-ci or micromasters-rc:

<img width="1364" alt="screen shot 2016-06-06 at 11 24 46 am" src="https://cloud.githubusercontent.com/assets/430126/15827506/64702104-2bd9-11e6-8c5b-9dc1cf6b57d6.png">

In the default state, and when individual learner is selected, the institution and comment fields should not display.

**Comment by amir-qayyum-khan** [comment]
@pdpinch hello,

The issue is in deployment of https://micromasters-rc.herokuapp.com,
- you cannot able to open my files from source of home page for example https://micromasters-rc.herokuapp.com/static/bundles/js/home_page/custom.js
- But you can open the public.js file which is existing deployed. https://micromasters-rc.herokuapp.com/static/bundles/public.js

You can check you self by right clicking the home page and the opn view as source link

<img width="1280" alt="screen shot 2016-06-07 at 4 43 38 pm" src="https://cloud.githubusercontent.com/assets/10431250/15856476/0d0bc426-2ccf-11e6-8a70-7d6ce323ca92.png">

##### Note: on my local docker machine it is working as expected. the issue is with location of static/assets of micromasters-rc.

**Comment by pdpinch** [comment]
@bdero @blarghmatey what's going on here with the static asset build (on both micromasters-ci and micromasters-rc)

**Comment by bdero** [comment]
I'm looking into this.

**Comment by bdero** [comment]
Nevermind, Tobias is working on this.

**Comment by pdpinch** [comment]
This was fixed by #493
