### ISSUE TITLE
Remove legacy pearson code

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4754]
We should investigate what is required to remove the unused pearson code. One key thing is we don't want to lose any data during this.

- [ ] Take a look at what code is present and categorize it
- [ ] Evaluate w/ the team how much of this code can be safely removed
- [ ] Remove that code

**Comment by pdpinch** [comment]
@annagav can you take a first pass on this?

In particular if we can identify the bits that depend on boto and target them for removal, it would help expedite #4753

**Comment by annagav** [comment]
Here are my findings:
/exams/management/commands:
- resync_exam_profiles
- simulate_sftp_responses
- simulate_sftp_responses_test
/exams/person: (could be removed since it is mostly the communication with Pearson)
/exams:
still in use
- models.py (contains `ExamRun` and `ExamProfile`)
- signals.py
- tasks.py (exam authorization  logic)
can be removed:
- urls.py
- utils.py (partially)
- views.py
