### ISSUE TITLE
CMS: add Hubspot form to "Benefits" page template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4758]
As a MicroMasters B2B salesperson, I'd like to add an optional contact form to the "Benefits" page type.  (The "Benefits" page template is actually a generic page template, but we unfortunately named it "Benefits" after the first use case) 

#### Designs and Mockups

TBD. Please make a draft first and then we can adjust the styling. 

#### Acceptance Criteria:

- [ ] Do a little research to determine the best way to add embedded HTML into a Wagtail template
- [ ] Update this ticket with description of how the form can be added
- [ ] Allow the CMS user to optionally add a custom form like the following to any "Benefits" page type
```
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>
<script>
  hbspt.forms.create({
	portalId: "8677455",
	formId: "1b63db1a-eb3a-45d6-82f1-c4b8f01835dc"
});
</script>
```

#### Related issues

- the home page redesign in #4736 includes a link to an "enterprises and institutions" page which would use this feature

**Comment by umarmughal824** [comment]
@pdpinch Here is my findings. 
It can be done via the following ways

1. By adding JS script support in `RichTextField` as it does not come by default. We will have to update it that will be applied to all the `RichTextField` across the whole website. But it could lead to **`XSS(Cross-Site Scripting)` malicious attacks**. **It's a bit trickier as they don't recommend it**. This is how it's going to look like
<img width="1251" alt="Screenshot 2021-01-22 at 15 01 32" src="https://user-images.githubusercontent.com/4043989/105476838-e7f5f980-5cc2-11eb-874c-54d5b955787a.png">

2. By using `RawHTMLFields` that again could lead to **`XSS(Cross-Site Scripting)` malicious attacks** so in order to use that we will have to trust the admins who will be adding that JS script. We need to keep in mind that our script could do anything malicious. **I wouldn't recommend that.**. This is how it looks like
<img width="1247" alt="Screenshot 2021-01-22 at 15 17 40" src="https://user-images.githubusercontent.com/4043989/105478494-107ef300-5cc5-11eb-8ed6-07cbda010c87.png">

3. By using a flag to show/hide the Hubspot form via `BooleanField`. This is how it looks like. 
<img width="1243" alt="Screenshot 2021-01-22 at 15 02 20" src="https://user-images.githubusercontent.com/4043989/105476885-f9d79c80-5cc2-11eb-99dd-08bc802cb839.png">

4. Or I made a custom element, it would add the form as the Hubspot form template is attached with it. This is how it looks like
<img width="1253" alt="Screenshot 2021-01-22 at 15 02 27" src="https://user-images.githubusercontent.com/4043989/105476914-03610480-5cc3-11eb-8afa-085596034043.png">

**This is how form looks like this on the page**

<img width="1438" alt="Screenshot 2021-01-22 at 15 13 14" src="https://user-images.githubusercontent.com/4043989/105477990-6c954780-5cc4-11eb-9b89-247261084acf.png">

**Note: I will never recommend the first two options as the admin/user could add anything suspicious or malicious by mistake or a bad intention. It could be anything from tracking, playing, or deleting the server files or hacking, etc.**

**Comment by pdpinch** [comment]
Thanks @umarmughal824. I think that's good advice about options 1 and 2. 

I'm not sure I understand the difference between 3 and 4. 

For the rendering, I'd like to try displaying the form (optionally) on the right side of "benefits" pages. I believe the current layout just uses columns 1-8 and leaves 9-12 empty.

**Comment by umarmughal824** [comment]
The third one is like a flag for showing or hiding the form and the fourth one is just like the form is embedded in that element. So if we want to remove the form, we just need to delete the element and vice versa. 

We can customize the rendering as per our needs.

**Comment by pdpinch** [comment]
So for option 3, the CMS user would have to uncheck the box for most uses of this form? 

I think option 4 sounds best for the CMS user.

**Comment by pdpinch** [comment]
Ferdi's pointed out that CMS users don't really need to know about this feature, since it will only appear on the page at `/organizations`

Can we add a conditional to the template that displays the form if the path starts with `/organizations` ?

**Comment by umarmughal824** [comment]
Yeah its feasible
