### ISSUE TITLE
Search: move reindex into a celery task

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4959]
We tried to rebuild the learner index, but the Heroku dyno timed-out before it could complete. Reindex should be set up to run as a celery task.

**Comment by arslanashraf7** [comment]
@pdpinch, While working on this I saw a few things and had some assumptions that I'm posting here for more clarity.

**_Assumption:_** I'm assuming that we usually run the reindexing through https://github.com/mitodl/micromasters/blob/master/search/management/commands/recreate_index.py command which then uses the https://github.com/mitodl/micromasters/blob/master/search/indexing_api.py#L575 for further operations. You can let me know if I'm missing something in this assumption.

**Questions1:** If we are trying to run this `recreate_index` asynchronously, we might need to keep a `synchronous` version of this because in some usages, e.g. https://github.com/mitodl/micromasters/blob/master/search/base.py#L21 we might still need to run reindexing synchronously. Should we keep this concern in mind?

**Questions2:** This is partially related to question#1, Instead of making the whole `create_reindex` running asynchronously through celery, shouldn't we go for creating subtasks for https://github.com/mitodl/micromasters/blob/master/search/indexing_api.py#L604 and https://github.com/mitodl/micromasters/blob/master/search/indexing_api.py#L612 and then group and run these subtasks parallelly inside re-index?

Although, I've created a WIP [PR](https://github.com/mitodl/micromasters/pull/4960/files) that just runs the `recreate_index` command through a celery task as a whole.

**Comment by pdpinch** [comment]
@rhysyngsun or @noisecapella can please advise?

**Comment by rhysyngsun** [comment]
@arslanashraf7 the `recreate_index` command in Open is probably your best reference for how this should be implemented. The use case in that project is much more complicated than we need here. The general strategy is what you suggested in Question 2:

https://github.com/mitodl/open-discussions/blob/master/search/tasks.py#L699

I suspect you'll see some differences between some of the lower-level elasticsearch APIs, so this might be something we need to split across a couple of PRs to bring MicroMasters up to speed with the umproved implementation in Open.

**Comment by arslanashraf7** [comment]
@rhysyngsun Thanks for providing the details on this one. I'll take a look at the referenced Open-discussion link.

>so this might be something we need to split across a couple of PRs

Based on the above understanding of dividing this into multiple PRs, do you think we could start with [this PR](https://github.com/mitodl/micromasters/pull/4960) which runs the reindexing as a whole in a celery task or do you think its invalid at this moment?

**Comment by arslanashraf7** [comment]
Shipped to production.
