### ISSUE TITLE
enroll and pay buttons link to mitxonline for DEDP

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5228]
### acceptance criteria, for the DEDP program

  - [ ] buttons for "audit for free" should use mitxonline's enrollment API (they do this already when the financial aid switch is set to true) 
  - [ ] buttons for "pay now" should link into the mitxonline checkout cart, with the course key passed in

**Comment by arslanashraf7** [comment]
>buttons for "audit for free" should use mitxonline's enrollment API (they do this already when the financial aid switch is set to true)

For the above, I was looking around the code and it looks like the enrollment API for Audit enrollment isn't actually dependent upon the `financial aid switch` but the courseware backend that's associated with a course run. e.g. If the courseware backend for a course run is set to `mitxonline` it would fetch the social auth of the user for that specific backend and then try to enroll on that backend's BASE_URL. [This implementation is here](https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L84-L111). 

But let's confirm this with @annagav if there are other places this might not be the case.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/34372316/194303200-2d9461cc-ef56-4d0e-bd25-e633125ad54e.png">


So, for Audit, we can just change the courseware backend to `mitxonline` instead of `edxorg`.

FYI, @pdpinch

**Comment by pdpinch** [comment]
All the MITxT courses should be already set to use `mitxonline` as the backend.

**Comment by arslanashraf7** [comment]
> When financial aid is turned off, does the Pay button respect the backend setting?

I don't think `Pay Now` button is respecting the setting, For mitxonline and edxorg course it takes the user to edX staging server.

The `Audit for Free and pay later` button does respect the courseware backend though. 

For the `Pay Now` button I've made some tweaks in [this PR](https://github.com/mitodl/micromasters/pull/5233) to take it to MITxOnline cart but I've conditioned it based on [DEDP Program courses](https://github.com/mitodl/micromasters/pull/5233/files#diff-d5de5fce23898af38cf96ba73fbdae70cb947ffae1e47551a73f5fccbabadaf9R191-R196), not the backend or financial aid flag. Should I put any additional conditions except from DEDP program?

**Comment by arslanashraf7** [comment]
In addition let me add references from code for morre clarity (Atleast from what i understand)

**On the frontend**
- We do have a financial availability check but that's meant to take the user to order summary page if enabled [Here is reference](https://github.com/mitodl/micromasters/blob/master/static/js/components/CourseEnrollmentDialog.js#L43-L61). If not enabled it tries to checkout right away.

**On the backend**
- When checkout call arives on the backend it lands [here](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L66). Now here we check the financial aid again. If Enabled it [tries to create the order ](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L85). If Disabled it [tries to enroll the user in Edx without caring for courseware backend ](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L128-L130) and that's why i think it's taking the user to edX.

**Comment by pdpinch** [comment]
> On the frontend
> We do have a financial availability check but that's meant to take the user to order summary page if enabled [Here is reference](https://github.com/mitodl/micromasters/blob/master/static/js/components/CourseEnrollmentDialog.js#L43-L61). If not enabled it tries to checkout right away.

This is fine. Even on the mitxonline checkout page, the user will have a link to request financial assistance. 

> On the backend
> When checkout call arives on the backend it lands [here](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L66). Now here we check the financial aid again. If Enabled it [tries to create the order ](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L85). If Disabled it [tries to enroll the user in Edx without caring for courseware backend ](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L128-L130)and that's why i think it's taking the user to edX.

Ok. I think we need to change this behavior to take into account the courseware backend.

**Comment by pdpinch** [comment]
> If Disabled it [tries to enroll the user in Edx without caring for courseware backend ](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L128-L130)and that's why i think it's taking the user to edX.

To be more specific, if the backend is mitxonline, I think we need to go to /cart/add?course_id=[url encoded course key]

**Comment by arslanashraf7** [comment]
> > If Disabled it [tries to enroll the user in Edx without caring for courseware backend ](https://github.com/mitodl/micromasters/blob/master/ecommerce/views.py#L128-L130)and that's why i think it's taking the user to edX.
> 
> To be more specific, if the backend is mitxonline, I think we need to go to /cart/add?course_id=[url encoded course key]

Thanks for clarifying, I've implemented this behavior in https://github.com/mitodl/micromasters/pull/5233.
