### ISSUE TITLE
django admin for program letters

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5256]
As an admin, it would be convenient to have a django admin for program letters, where I can search and create new ones. 

#### Acceptance Criteria:

- [ ] list view should include search by user email
- [ ] would be nice if list view can include filter by program
- [ ] detail view displays creation date and last updated date
- [ ] allow creating new letters

**Comment by arslanashraf7** [comment]
Since we are working on this, Would it be fine to add another case that I noticed? 

So with https://github.com/mitodl/micromasters/pull/5253 merged we have shifted the letters to be visible when active and also validated the existing letters to mark as inactive.

Based on the above, and the existing implementation of the [letter generation function](https://github.com/mitodl/micromasters/blob/master/grades/api.py#L282) checks if a letter already exists before creating a new one. This could be a problem for the letters that already exist but are inactive now and it's possible that the user can complete these program(s) at some point in the future. In that case, we should mark their existing letter as active. So [this logic](https://github.com/mitodl/micromasters/blob/master/grades/api.py#L282) needs to be changed a bit to handle that case.

**Comment by pdpinch** [comment]
Sure. Please open a new issue. 

I think these should be separate PRs, but if you want to put them both into one that’s OK with me.

**Comment by arslanashraf7** [comment]
> Sure. Please open a new issue. I think these should be separate PRs, but if you want to put them both into one that’s OK with me.

Created https://github.com/mitodl/micromasters/issues/5257
