### ISSUE TITLE
Remove Exam Card on dashboard

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#5282]
Remove the card about exams:
<img width="783" alt="211564043-2aee7800-a2f3-4086-9a63-0513ef540775" src="https://user-images.githubusercontent.com/7574259/211611416-6fe9a878-f2da-4707-bac4-8d011255a478.png">

**Comment by arslanashraf7** [comment]
So I was looking at this and it turns out that this card is already behind a feature flag `FEATURE_TURN_PAYMENT_OFF`, If the flag is on the card hides otherwise it shows. When I mentioned this card [in another PR review](https://github.com/mitodl/micromasters/pull/5278#pullrequestreview-1242200391) I didn't have this flag turned on so I was able to see this card.

[Here](https://github.com/mitodl/micromasters/blob/master/static/js/containers/DashboardPage.js#L950-L959) is he code where it is happening.

I think the current behavior is fine having it hidden behind a feature flag, but if we should remove it we can create a PR for that.

**Comment by annagav** [comment]
@arslanashraf7 I think it is time to remove the that feature flag.

**Comment by arslanashraf7** [comment]
@annagav I've removed the card & feat flag in https://github.com/mitodl/micromasters/pull/5289.

**Comment by pdpinch** [comment]
Can we turn off the flag today, while we're waiting for the PR to be reviewed, merged and deployed?

**Comment by arslanashraf7** [comment]
> Can we turn off the flag today, while we're waiting for the PR to be reviewed, merged and deployed?

Yes, we should simply be able to do that from Heroku dashboard. I can do that. Do you want to turn it off on RC  production too?

**Comment by annagav** [comment]
No, we don't want to turn this feature off. It will show the Proctored Exam card again. Why do you want to turn it off?

**Comment by annagav** [comment]
This is complete now
