### ISSUE TITLE
Test edx login with new OAuth library

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#59]
As a user, I would rather not have to approve micromasters access to edX every time I make a request from edX. 

The current edX OAuth library is incomplete and doesn't store user access tokens, so  a new one must be requested each time. 

The library being added by PR https://github.com/edx/edx-platform/pull/11449 should address the issue. We should test our login flow with this library, and +1 the PR.

**Comment by pdpinch** [comment]
FWIW, e0d from edX devops mentioned yesterday that the migrations for this PR are particularly complex.

**Comment by pdpinch** [comment]
@giocalitri what should we do with this issue? Do you think we can/should pursue it next sprint, or do we need to put it on hold until edX actually merged the new OAuth library?

**Comment by giocalitri** [comment]
I have had some suggestions about how to run the migrations, but I want to create a different devstack to test it. I think it would be useful to test it, especially if we end up finding missing features/problems.

The suggestion about the migration was:
That is expected behavior (unfortunately).  The short version is that you need to run `./manage.py migrate —fake oauth2_provider zero`, followed by `./manage.py migrate —fake-initial`
The implementation is a work in progress, but the end goal is to support the new library (django-oauth-toolkit) with no client-side changes.  All you will need to do is create a client_id (which can be done from the django admin under `django-oauth-toolkit -> Applications`), and then use that client_id to get an access token.
Old client_ids will still use the old behavior.
The caveat is that we’ve only implemented some of the full interface in a backward compatible way (under the URL prefix /oauth2/).  The rest is available for testing purposes under /_o/.  We don’t intend for that to be used publicly, and will be removing it eventually, but you can use any of the URLs under there to test out your app and get it working.  Then if you’ll tell us which pieces you needed from there, we can prioritize creating the mapping under /oauth2/.  Thanks for your interest in this code.

**Comment by pdpinch** [comment]
A new devstack and Vagrantfile was announced today, ostensibly to address this migration issue. 

https://groups.google.com/d/msgid/edx-code/CAKPrGxhoytRL_i%2ByvfNzfdQRwCCca1%2BwgEK7mrTR3%3D%3Dz%3DvXKhg%40mail.gmail.com?utm_medium=email&utm_source=footer

However, at the moment, it's not working for me.

**Comment by pdpinch** [comment]
The new library has two issues:

- [ ] it doesn't use the template that we had written for the old library
- [ ] it doesn't fix the session issue that we had with old library: authorizations don't persist.
