### ISSUE TITLE
Dashboard: Learners near me component

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#600]
As a learner, I'd like to be able to identify learners who are geographically close to me, so that I might communicate with them. For MVP, "geographically close" will be defined as within the same region.

![image](https://cloud.githubusercontent.com/assets/430126/18281159/d964102c-7429-11e6-83f3-76ab0e36ba70.png)
# Acceptance Criteria
- [ ] Widget uses a query based on the current program and user's **region** to fetch up to 8 avatars
- [ ] The count of all learners matching the query appears at the top
- [ ] Clicking on the count leads to the learners searching learners view using the same region query
- [ ] "view all learners" links to the learners searching learners view with no filters
# Related Issues
#935 Learners search for learners

**Comment by roberthouse54** [comment]
To do this, I think we will need to change how we are getting the user's current location. Currently, they just type their City in a freeform text field. We will want to use some sort of mapping api so we can actually get a user's LAT/LONG.

**Comment by giocalitri** [comment]
I think that a good very first approach might be to match by region: this still does not solve all the problems, but it is better than matching by city.

**Comment by roberthouse54** [comment]
I concur with this idea.

**Comment by pdpinch** [comment]
I updated the description with our decision to use region, and with the current design. This isn't a discovery story any more.

**Comment by pdpinch** [comment]
I updated the screenshot and added acceptance criteria.

**Comment by roberthouse54** [comment]
A note: Please ignore the green dots in the mock. They were meant to indicate "online now" for a chat type feature, which we obviously do not have.

**Comment by alvinsiu** [comment]
How are we defining region?  Is that country and state/territory?

**Comment by giocalitri** [comment]
I do not think this story is MVP and this feature should not go in the codebase before the deadline.

**Comment by roberthouse54** [comment]
We will display a "Users Near Me" card on the dashboard in the right column, below the “Progress” card.

![image](https://cloud.githubusercontent.com/assets/20047260/21362255/85fff408-c6b5-11e6-828b-116b08ddd46f.png)


For users who have entered their Street Address in Google Places, we will display the results immediately. For students for whom we only know City/State/Country, we will prompt the user to enter their geo-location (address) in order to use this feature. 

![image](https://cloud.githubusercontent.com/assets/20047260/21362197/58743724-c6b5-11e6-90ae-94452a5401bf.png)

Clicking “Update your address” will open a dialog to capture the location (Google places) field only. 

![image](https://cloud.githubusercontent.com/assets/20047260/21362208/5ec67c68-c6b5-11e6-9876-04b5ee5fde2f.png)

After entering the address and clicking submit, we will display the first 8 results of users using LAT-LONG + distance, sorting by closest first (and perhaps filtering to not display users who do not have a photo). We will show up to 8 results in this box, and a link to “View All” which will go to the pre-filtered view of the Learner Search.

![image](https://cloud.githubusercontent.com/assets/20047260/21362225/6b88c6ea-c6b5-11e6-8813-cf52cc30c6fc.png)

**Comment by roberthouse54** [comment]
Closing this in favor of https://github.com/mitodl/micromasters/issues/2516
