### ISSUE TITLE
Student dashboard: "Apply" Button

### ISSUE THREAD

**Issue by jamiefolsom** [mitodl/micromasters#64]
As a student, I want to be able to apply for admission to a micromasters program.

This requires a button on the course listing for a given program, which appears, disabled, until criteria for application have been met. 

Then the button should appear enabled, and when clicked, load an application form.

**Comment by pdpinch** [comment]
I don't think this quite right. The student is a member of the micromasters program just by creating an account on the micromasters site. There's no additional application necessary. However, we do need an indicator so that the learner knows what tasks she still has to complete to get her certificate. 

We also need a button to upsell those who have received their credential to apply for the on-campus SCM program. See #100
