### ISSUE TITLE
Add MicroMasters program enrollment to user model 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#672]
As a learner and as a MicroMasters team member, I want the portal to recognize what specific MicroMasters I am part of. 

We need to add this to the user model (foreign key(s) to programs), and also determine how best to populate it. For now, we will assume that if the user is enrolled in any courserun associated with a particular MM program, they qualify as enrolled. 

We'll need to update this whenever we update the user's enrollments. 

depends on the story about enrollment models #677

**Comment by pdpinch** [comment]
Or we can calculate this from the user's enrollments

**Comment by gsidebo** [comment]
if we're adding a reference to a user's Enrollments, we should do the same for Certificates. both of them have foreign keys to a User. pretty sure they would just need a 'related_name' like Education or Employment have in their ForeignKey relationship with Profile

**Comment by gsidebo** [comment]
@annagav are you back on this or is @giocalitri working on it? this has some implications for #682. i think it make sense to add a user's overall program grade to this model, which we would use when filtering users by grade. we could push that to a different issue, but #682 depends on having a pre-calculated average grade for a program and this issue seems like a good place to address that

**Comment by giocalitri** [comment]
the PR is open for review
