### ISSUE TITLE
create realistic fake users for testing learner profile search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#675]
We'll want to cover at least two values in each facet.

**Comment by pdpinch** [comment]
Can we just update factoryboy to do this? Will it work for the more complex fields, like field of study and contry/region?

**Comment by pdpinch** [comment]
Some tools that might help:

https://randomuser.me/
http://uifaces.com/
http://uinames.com/

**Comment by gsidebo** [comment]
@pdpinch just want to make sure i know what you mean by "We'll want to cover at least two values in each facet." does that mean we want our combined set of fake users to cover at least 2 distinct values for everything listed under "Fields for faceting" in #669 ? (completed courses, completed course grade, currently enrolled, etc...)

**Comment by gsidebo** [comment]
@pdpinch another question: since you're asking for **realistic**-looking fake users, I'm guessing that you want some push-button way to create the users and save them to the DB, after which you would use the app as normal and see the fake users in search results. Is that correct? If so, we would need a way to populate the database with these users, but only for non-production environments. A couple options would be (1) a new migration that inspects the deployment type, or (2) API endpoint(s) that are only accessible if the app isn't in production

If that's not correct and we only want test users for unit tests, I don't think they need to be realistic.

**Comment by noisecapella** [comment]
@gsidebo Yes, we should have a management script to create realistic fake users so we can experiment with the UI and feel like the data is realistic

**Comment by noisecapella** [comment]
We should avoid code which should run only in a particular place. The management command would only be run once so I feel like the inconvenience is small there

**Comment by gsidebo** [comment]
per conversation with @noisecapella, this story is going to depend on #711 and possibly #672. those stories will enable us to add enrollments, certificates, and (possibly) grades in MicroMasters (as opposed to edX). in the meantime, i'm working on creating fake users with data in our existing models (Profile, Employment, Education, etc)

**Comment by gsidebo** [comment]
getting profile images for these users will depend on #394. the randomuser.me API gives us images, but we'll need that issue to be done before we can use them

**Comment by pdpinch** [comment]
We'll do separate stories to deal with enrollments, certificates and profile images -- when those are ready.
