### ISSUE TITLE
Add program enrollments to fake users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#842]
For testing and demo purposes, I need fake users to show up in search results, which requires they be enrolled in a program.

**Comment by gsidebo** [comment]
The user generation script creates fake users AND fake programs/courses (and obviously creates relationships between the two). This decision was made in order to make the script 'data-agnostic', so to speak. Different environments are going to have different programs/courses available in the database (or no programs/courses at all). Generating fake programs ensures that we aren't relying data that might not be there, and it gives us flexibility with the distribution of courses among the users. The fake programs as they exist right now are "Digital Learning" and "Analog Learning", and both have 3 courses each. **The fake users should be showing up in search results under those programs after the script is run**. If that's not happening, that's a bug.

With that said: are we requesting that we add the ability to assign fake users to live courses? That can be done with some tinkering. Is there a reason that the fake programs aren't sufficient here? Creating relationships between test/'fake' data and live data could carry some problems with it, though it wouldn't matter so much in non-production environments. There are also some potential problems with program data being different across environments

**Comment by pdpinch** [comment]
I didn't know about the fake programs. I think the thing I need to do is give myself a staff or instructor roll on the programs in question.

**Comment by gsidebo** [comment]
ah, i completely forgot about instructor roles for this. it wouldn't be a problem to add an option to take a username and assign that user as an instructor on all of the fake programs. we can also print out a message when the generation script is run _without_ an instructor username to say that these fake programs wouldn't be viewable until a user gets that role assignment. would that work for you?

**Comment by pdpinch** [comment]
I think I'm all set. I added an instructor role for my test user in a program with fake users, and now I'm able to see them all in search results.

**Comment by pdpinch** [comment]
We can check in on Tuesday to make sure we're on the same page.
