### ISSUE TITLE
Sign-up: Update UX for screen 2 - Education

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#929]
# Acceptance Criteria:

- [ ] defaults cards to nothing selected
- [ ] clicking yes will show the pop-up 
- [ ] hide yes/no option when an entry is added; 
- [ ] when all entries are deleted, the yes/no option should return
- [ ] ignore pre-existing edX data
- [ ] styling fixes

Should look like this:

![sign_up_2 2x](https://cloud.githubusercontent.com/assets/430126/18037934/f19db554-6d5c-11e6-92f2-71c93904dbbe.png)

**Comment by gsidebo** [comment]
@pdpinch description says 'defaults cards to “No”', screenshot indicates that cards should default to have no value selected at all

**Comment by roberthouse54** [comment]
@gsidebo You are correct. It should be defaults to nothing selected.

**Comment by gsidebo** [comment]
@pdpinch @roberthouse54 i just talked to alice. before this story, we have calculated the 'degree inclusions' for a user based on their edx level of education. example: if i indicated that i had a master's degree in edx, we would set the radio selection to 'yes' for every degree type up to and including master's. i know that the issue says that we should 'ignore pre-existing edX data', but i want to make sure that dropping this functionality is what we want

**Comment by pdpinch** [comment]
We decided it wasn't clear to the user why we were pre-setting some fields, and that it was best to ignore the edX data. 

Also, people's educational history isn't necessarily linear in the way we were assuming.

**Comment by gsidebo** [comment]
@pdpinch @roberthouse54 another question: the 'No' option for these 'Do you have' questions seems to be meaningless. A blank answer is effectively the same thing, and we don't have any use for the 'No' answer in particular. Given that, do we want to keep track of a user selecting 'No' for these questions? ie: a user selects 'No' on Master's degree, navigates backward/forward, then returns to the page and sees the 'No' selection still there. that will take a small amount of extra work. not too time-consuming, but i wanted to ask since (a) it isn't important for the overall functionality of the signup flow, and (b) keeping the Yes/No answer seems kind of fishy in general given the changes in this issue

**Comment by roberthouse54** [comment]
I think I disagree that no answer and no mean the same thing. We are not requiring any answer, but if they answer "No" then we have learned more about the user. If they do not answer, then we do not know whether they have a particular degree or not. Admittedly we have to real "use" for a no answer, but then again, we are not really using the yes answer either. Presumably it will just be data used in generating an application to the MIT Masters program.

**Comment by gsidebo** [comment]
> but if they answer "No" then we have learned more about the user

what i meant by them meaning the same thing is that we don't do anything with that 'No' answer in the data. both in terms of UI and our own data, a null answer is identical to a 'No' answer. that _is_ user input and i'm sure there are scenarios where it would be interesting to us, but we don't have any plans to keep track of it right now

**Comment by pdpinch** [comment]
@gsidebo @roberthouse54 Sorry I missed this. Yes, we want to capture the "No" state. Does that mean changes to the profile API and the model?
