### ISSUE TITLE
Instructor search: Update styling to match design

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#934]
Should look like:

![learner_search 2x](https://cloud.githubusercontent.com/assets/430126/18038529/4af8302a-6d67-11e6-8272-a4c77c6ba1d9.jpg)

Not:

![image](https://box.everhelper.me/attachment/560187/eb68aeb9-7366-4cd9-9ed9-edae1a1b5a5a/623857-zbunyYQDz9pf6RiV/screen.png)

# Acceptance Criteria

- [x] Remove tabs
- [x] Remove "New Group" button
- [ ] Change "Email Selected" button label to "Email These Learners"
- [x] left justify the list of countries in the "place of birth" facet
- [ ] Add disclosure triangles to hierarchical facets
- [ ] highlight (in green) the area between the handles in histogram facets
- [ ] Remove US states from search results
- [ ] Change "Place of Birth" facet label to "Country of Birth" (#851)
- [ ] Change "Current Location" facet label to "Current Residence" (#854)

# Related Issues

- #986 location facets should allow multiple selections
- facets should be open by default (US #931)
- Add city (3rd level) to location facet (US #932)
- Add current courses facet (US #933)

**Comment by roberthouse54** [comment]
I have made some of the css style tweaks to this page, but there are other changes that require more substantial coding. Adding to the list of requirements above:

- [ ] Change the Pagination to arrows instead of "Next\Previous"
- [ ] Add "Sort by:" to the sort filter only on the current selection.
- [ ] The "Clear Filters" link should be hidden when no filters are selected, and the entire line that the filters live on should also be hidden. 
- [ ] The filters in the left nav should be open by default.
- [ ] A larger issue: It seems that the search filters in the left are not additive. I thought we were making these additive, so that you could select both "Canada" and "United States" etc. The same logic would apply to the hierarchical filters, so you could select multiple states for example. This would require adding checkboxes to the filters. We need to clarify the logic here.
