### ISSUE TITLE
Search: location facets should allow multiple selections 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#986]
Users should be able to perform an "OR" search by selecting multiple locations from the "Current Residence" and "Country of Birth" facets.

for a functionality example, see the "country" facet at http://demo.searchkit.co/ 

# Acceptance Criteria

- [ ] User should be able to select more than one value for each of these facets above.
- [ ] checking a facet updates the search results (in the right pane) but not facet counts (left pane)

**Comment by gsidebo** [comment]
@pdpinch fyi: Place Of Birth facet is trivial since it uses a [Refinement List filter](http://docs.searchkit.co/stable/docs/components/navigation/refinement-list.html) which gives you the option to use an `OR` operator instead of `AND`. The Current Location facet is not so simple. It uses a [Hierarchical Menu filter](http://docs.searchkit.co/stable/docs/components/navigation/hierarchical-menu.html) which provides no such option. I spoke to Alice and she isn't aware of any quick workarounds. I also searched their github issues and did some general google searching - no one even seems to be asking about this type of functionality. I'll do more digging, but this seemed consequential enough to let you know about

**Comment by pdpinch** [comment]
What if we used [Hierarchical Refinement](http://docs.searchkit.co/stable/docs/components/navigation/hierarchical-refinement-filter.html) filter?

**Comment by gsidebo** [comment]
also no `operator` option

**Comment by Ferdi** [comment]
let's drop it. Leave Current Location as is (AND)

**Comment by gsidebo** [comment]
sounds good
